/* ===== PROFESYONEL & AKADEMİK ALANLAR =====
   g  : mini oyun motoru
   skin: motorun teması (aynı motor, farklı görsel)
*/
const ALANLAR = [
  /* — Mühendislik & Teknoloji — */
  {id:'ucak',      n:'Uçak Mühendisliği',    e:'✈️', g:'ucus',   skin:'plane',   a:'#7cb8ff', b:'#2f5bd0', grp:'Mühendislik'},
  {id:'uzay',      n:'Uzay & Astronomi',     e:'🚀', g:'ucus',   skin:'ship',    a:'#a78bfa', b:'#4c1d95', grp:'Mühendislik'},
  {id:'makine',    n:'Makine Mühendisliği',  e:'⚙️', g:'disli',  skin:'steel',   a:'#ffb47a', b:'#b45309', grp:'Mühendislik'},
  {id:'elektrik',  n:'Elektrik-Elektronik',  e:'⚡', g:'devre',  skin:'circuit', a:'#ffe066', b:'#d97706', grp:'Mühendislik'},
  {id:'yazilim',   n:'Yazılım Mühendisliği', e:'💻', g:'sirala', skin:'code',    a:'#7dd3fc', b:'#0369a1', grp:'Mühendislik'},
  {id:'yapayzeka', n:'Yapay Zekâ',           e:'🤖', g:'sirala', skin:'neural',  a:'#c4b5fd', b:'#5b21b6', grp:'Mühendislik'},
  {id:'insaat',    n:'İnşaat Mühendisliği',  e:'🏗️', g:'insa',   skin:'beton',   a:'#fcd34d', b:'#92400e', grp:'Mühendislik'},
  {id:'mimarlik',  n:'Mimarlık',             e:'📐', g:'insa',   skin:'mimar',   a:'#fda4af', b:'#9f1239', grp:'Mühendislik'},
  {id:'robotik',   n:'Robotik',              e:'🦾', g:'disli',  skin:'robot',   a:'#94a3ff', b:'#3730a3', grp:'Mühendislik'},
  {id:'otomotiv',  n:'Otomotiv',             e:'🚗', g:'disli',  skin:'motor',   a:'#ff9d9d', b:'#b91c1c', grp:'Mühendislik'},
  {id:'denizcilik',n:'Gemi & Denizcilik',    e:'🚢', g:'ucus',   skin:'boat',    a:'#67e8f9', b:'#0e7490', grp:'Mühendislik'},
  {id:'endustri',  n:'Endüstri Mühendisliği',e:'🏭', g:'sirala', skin:'fabrika', a:'#fdba74', b:'#9a3412', grp:'Mühendislik'},
  {id:'malzeme',   n:'Malzeme Bilimi',       e:'🧱', g:'insa',   skin:'kristal', a:'#d8b4fe', b:'#6b21a8', grp:'Mühendislik'},
  {id:'enerji',    n:'Enerji Sistemleri',    e:'🔋', g:'devre',  skin:'enerji',  a:'#86efac', b:'#15803d', grp:'Mühendislik'},
  {id:'cevre',     n:'Çevre Mühendisliği',   e:'♻️', g:'karisim',skin:'su',      a:'#5eead4', b:'#0f766e', grp:'Mühendislik'},

  /* — Sağlık — */
  {id:'tip',       n:'Tıp (Genel)',          e:'🩺', g:'teshis', skin:'klinik',  a:'#fca5a5', b:'#b91c1c', grp:'Sağlık'},
  {id:'cerrahi',   n:'Cerrahi',              e:'🔪', g:'hassas', skin:'ameliyat',a:'#7dd3fc', b:'#075985', grp:'Sağlık'},
  {id:'kardiyo',   n:'Kardiyoloji',          e:'❤️', g:'teshis', skin:'kalp',    a:'#fb7185', b:'#9f1239', grp:'Sağlık'},
  {id:'noroloji',  n:'Nöroloji',             e:'🧠', g:'devre',  skin:'sinir',   a:'#e9a8ff', b:'#7e22ce', grp:'Sağlık'},
  {id:'dis',       n:'Diş Hekimliği',        e:'🦷', g:'hassas', skin:'dis',     a:'#bae6fd', b:'#0284c7', grp:'Sağlık'},
  {id:'eczacilik', n:'Eczacılık',            e:'💊', g:'karisim',skin:'ilac',    a:'#c4b5fd', b:'#6d28d9', grp:'Sağlık'},
  {id:'beslenme',  n:'Beslenme & Diyetetik', e:'🥗', g:'karisim',skin:'gida',    a:'#bef264', b:'#4d7c0f', grp:'Sağlık'},
  {id:'fizyo',     n:'Fizyoterapi',          e:'🦴', g:'hassas', skin:'kas',     a:'#fdba74', b:'#c2410c', grp:'Sağlık'},
  {id:'veteriner', n:'Veterinerlik',         e:'🐾', g:'teshis', skin:'hayvan',  a:'#fcd34d', b:'#a16207', grp:'Sağlık'},
  {id:'psikoloji', n:'Psikoloji',            e:'🧩', g:'teshis', skin:'zihin',   a:'#f0abfc', b:'#86198f', grp:'Sağlık'},
  {id:'acil',      n:'Acil Tıp & Hemşirelik',e:'🚑', g:'sirala', skin:'triyaj',  a:'#fda4af', b:'#be123c', grp:'Sağlık'},
  {id:'radyoloji', n:'Radyoloji',            e:'🩻', g:'kazi',   skin:'rontgen', a:'#a5b4fc', b:'#3730a3', grp:'Sağlık'},

  /* — Temel Bilimler — */
  {id:'fizik',     n:'Fizik',                e:'⚛️', g:'nisan',  skin:'atom',    a:'#93c5fd', b:'#1d4ed8', grp:'Bilim'},
  {id:'kimya',     n:'Kimya',                e:'🧪', g:'karisim',skin:'lab',     a:'#67e8f9', b:'#0891b2', grp:'Bilim'},
  {id:'biyoloji',  n:'Biyoloji',             e:'🧬', g:'teshis', skin:'hucre',   a:'#86efac', b:'#166534', grp:'Bilim'},
  {id:'matematik', n:'Matematik',            e:'➗', g:'sirala', skin:'sayi',    a:'#fde68a', b:'#b45309', grp:'Bilim'},
  {id:'jeoloji',   n:'Jeoloji',              e:'🪨', g:'kazi',   skin:'kaya',    a:'#d6b48c', b:'#78350f', grp:'Bilim'},
  {id:'meteoroloji',n:'Meteoroloji',         e:'🌦️', g:'ucus',   skin:'balon',   a:'#bae6fd', b:'#0369a1', grp:'Bilim'},
  {id:'okyanus',   n:'Okyanus Bilimi',       e:'🌊', g:'ucus',   skin:'sub',     a:'#5eead4', b:'#115e59', grp:'Bilim'},
  {id:'genetik',   n:'Genetik',              e:'🧫', g:'teshis', skin:'dna',     a:'#a5f3fc', b:'#0e7490', grp:'Bilim'},

  /* — Doğa & Yeryüzü — */
  {id:'ziraat',    n:'Ziraat & Tarım',       e:'🌾', g:'karisim',skin:'tarla',   a:'#fde047', b:'#854d0e', grp:'Doğa'},
  {id:'orman',     n:'Ormancılık & Ekoloji', e:'🌲', g:'kazi',   skin:'orman',   a:'#6ee7b7', b:'#065f46', grp:'Doğa'},
  {id:'arkeoloji', n:'Arkeoloji',            e:'🏺', g:'kazi',   skin:'antik',   a:'#fcd34d', b:'#92400e', grp:'Doğa'},
  {id:'madencilik',n:'Madencilik',           e:'⛏️', g:'kazi',   skin:'maden',   a:'#cbd5e1', b:'#475569', grp:'Doğa'},
  {id:'cografya',  n:'Coğrafya',             e:'🗺️', g:'kazi',   skin:'harita',  a:'#7dd3fc', b:'#1e40af', grp:'Doğa'},

  /* — Sosyal & İş — */
  {id:'hukuk',     n:'Hukuk',                e:'⚖️', g:'teshis', skin:'adalet',  a:'#e2e8f0', b:'#334155', grp:'Sosyal'},
  {id:'ekonomi',   n:'Ekonomi & Finans',     e:'📈', g:'sirala', skin:'borsa',   a:'#86efac', b:'#15803d', grp:'Sosyal'},
  {id:'isletme',   n:'İşletme & Girişimcilik',e:'💼',g:'sirala', skin:'ofis',    a:'#fbbf24', b:'#a16207', grp:'Sosyal'},
  {id:'egitim',    n:'Eğitim Bilimleri',     e:'🎓', g:'ritim',  skin:'okul',    a:'#c4b5fd', b:'#5b21b6', grp:'Sosyal'},
  {id:'medya',     n:'Gazetecilik & Medya',  e:'📰', g:'sirala', skin:'haber',   a:'#e5e7eb', b:'#374151', grp:'Sosyal'},
  {id:'tarih',     n:'Tarih',                e:'🏛️', g:'sirala', skin:'antikcag',a:'#fcd9a0', b:'#92400e', grp:'Sosyal'},
  {id:'dilbilim',  n:'Dilbilim & Çeviri',    e:'🗣️', g:'ritim',  skin:'harf',    a:'#f9a8d4', b:'#9d174d', grp:'Sosyal'},
  {id:'muzik',     n:'Müzik',                e:'🎼', g:'ritim',  skin:'nota',    a:'#f0abfc', b:'#7e22ce', grp:'Sosyal'},
  {id:'sanat',     n:'Görsel Sanatlar',      e:'🎨', g:'hassas', skin:'tuval',   a:'#fda4af', b:'#be185d', grp:'Sosyal'},
  {id:'ascilik',   n:'Aşçılık & Gastronomi', e:'👨‍🍳', g:'karisim',skin:'mutfak',a:'#fdba74', b:'#c2410c', grp:'Sosyal'},
];

/* ===== KONULAR: her alan 12 konu — [başlık, bilgi] ===== */
const KONULAR = {};

Object.assign(KONULAR, {
ucak: [
 ['Kaldırma Kuvveti','Kanadın üstünde hava daha hızlı akar, basınç düşer ve uçak yukarı doğru itilir.'],
 ['Hücum Açısı','Kanadın havayla yaptığı açı arttıkça kaldırma büyür; belli bir sınırdan sonra akış kopar ve uçak perdövites yapar.'],
 ['Sürüklenme','Havanın uçağı geriye çeken direncidir ve hız arttıkça yaklaşık karesiyle büyür.'],
 ['İtki','Motorun ürettiği ileri kuvvettir; sürüklenmeyi aştığı sürece uçak hızlanmaya devam eder.'],
 ['Kanat Profili','Kanadın kesit şekli, kaldırma ile sürüklenme arasındaki dengeyi belirleyen en kritik tasarım kararıdır.'],
 ['Kanatçık','Kanat uçlarındaki hareketli yüzeyler zıt yönde çalışarak uçağı yatırır ve dönüşü başlatır.'],
 ['Flap','İniş ve kalkışta kanadın alanını ve kamburluğunu artırarak düşük hızda kaldırma sağlar.'],
 ['Winglet','Kanat ucundaki yukarı kıvrım, uç girdaplarını küçültür ve yakıt tüketimini gözle görülür azaltır.'],
 ['Turbofan Motor','Havanın büyük bölümünü motorun etrafından geçirir; bu sayede hem verimli hem sessizdir.'],
 ['Mach Sayısı','Uçağın hızının o irtifadaki ses hızına oranıdır; 1 Mach tam ses hızı demektir.'],
 ['Ağırlık Merkezi','Uçağın dengesi, ağırlık merkezinin kaldırma merkezine göre konumuna bağlıdır; yanlış yükleme uçuşu tehlikeye atar.'],
 ['Yorulma Çatlağı','Metal gövde tekrarlayan basınç döngüleriyle zamanla çatlar; bu yüzden uçak ömrü uçuş saatiyle sınırlanır.'],
],
uzay: [
 ['Yörünge','Yörünge, düşmeye devam ederken yatayda o kadar hızlı gitmektir ki yeryüzünü sürekli ışkalarsın.'],
 ['Kaçış Hızı','Dünya’nın çekiminden tamamen kurtulmak için gereken hız saniyede yaklaşık 11,2 kilometredir.'],
 ['Roket Denklemi','Bir roketin ulaşabileceği hız, yakıt oranının logaritmasıyla artar; bu yüzden roketler çoğunlukla yakıttır.'],
 ['Kademeli Roket','Boşalan yakıt tankını atmak, ölü ağırlıktan kurtularak kalan kısmı çok daha hızlandırır.'],
 ['Yerçekimi Sapanı','Bir gezegenin yanından geçen sonda, gezegenin hareketinden hız ödünç alarak yakıtsız hızlanır.'],
 ['Işık Yılı','Işığın bir yılda aldığı yoldur, yaklaşık 9,46 trilyon kilometre; zaman değil mesafe birimidir.'],
 ['Kızıla Kayma','Uzaklaşan galaksilerin ışığı kızıla kayar; evrenin genişlediğini bu sayede anladık.'],
 ['Kara Delik','Kütlesi o kadar yoğundur ki belirli bir sınırın içinden ışık bile kaçamaz.'],
 ['Lagrange Noktası','İki büyük cismin çekimlerinin dengelendiği noktalardır; teleskoplar buralara park edilir.'],
 ['Güneş Rüzgârı','Güneş’ten sürekli akan yüklü parçacıklar, kutuplarda auroraları oluşturur.'],
 ['Gezegen Geçişi','Bir gezegen yıldızının önünden geçerken ışığı hafifçe azalır; öte gezegenleri böyle buluruz.'],
 ['Isı Kalkanı','Atmosfere giren araç sürtünmeyle binlerce dereceye ulaşır; kalkan eriyerek ısıyı taşır.'],
],
makine: [
 ['Tork','Bir kuvvetin döndürme etkisidir; kuvvet ile kol uzunluğunun çarpımına eşittir.'],
 ['Dişli Oranı','Küçük dişli büyük dişliyi döndürünce hız azalır ama tork artar; bu bir değiş tokuştur.'],
 ['Kayış-Kasnak','Uzak iki mili birbirine bağlar; kayma payı sayesinde ani yüklerde sistemi korur.'],
 ['Rulman','Sürtünmeyi kaymadan yuvarlanmaya çevirerek enerji kaybını büyük ölçüde düşürür.'],
 ['Termodinamiğin 1. Yasası','Enerji yoktan var olmaz; sadece biçim değiştirir ve bir kısmı hep ısıya gider.'],
 ['Verim','Hiçbir makine %100 verimli değildir; sürtünme ve ısı kaybı her zaman pay alır.'],
 ['Krank Mekanizması','Doğrusal pistonu dönme hareketine çevirir; içten yanmalı motorun kalbidir.'],
 ['Hidrolik','Sıkıştırılamayan sıvı basıncı ilettiği için küçük kuvvetle büyük yükler kaldırılır.'],
 ['Yorulma Dayanımı','Parçalar kopma yükünün çok altında bile, tekrarlayan yükler altında kırılabilir.'],
 ['Titreşim','Her yapının doğal frekansı vardır; dışarıdan aynı frekansta zorlama gelirse rezonansla büyür.'],
 ['Tolerans','İki parçanın birbirine geçmesi için ölçüler değil, ölçü aralıkları tasarlanır.'],
 ['Yağlama','Yağ filmi iki metal yüzeyi ayırır; temas kalkınca aşınma neredeyse durur.'],
],
elektrik: [
 ['Ohm Yasası','Gerilim, akım ile direncin çarpımına eşittir; devre çözümlemesinin temel denklemidir.'],
 ['Seri Devre','Akım tek yol izler; bir eleman koparsa tüm devre durur.'],
 ['Paralel Devre','Akım kollara ayrılır; bir kol kopsa bile diğerleri çalışmaya devam eder.'],
 ['Kısa Devre','Direnç neredeyse sıfıra düşünce akım fırlar; sigorta tam da bunu kesmek için vardır.'],
 ['Alternatif Akım','Yön ve büyüklüğü sürekli değişir; uzun mesafeye taşımak doğru akımdan çok daha verimlidir.'],
 ['Transformatör','Manyetik alan üzerinden gerilimi yükseltir ya da düşürür; sadece alternatif akımda çalışır.'],
 ['Kapasitör','Enerjiyi elektrik alanında biriktirir ve gerektiğinde çok hızlı boşaltır.'],
 ['Bobin','Akım değişimine direnir; enerjiyi manyetik alanda saklar.'],
 ['Diyot','Akımı yalnız tek yönde geçirir; doğrultmanın temel taşıdır.'],
 ['Transistör','Küçük bir sinyalle büyük akımı kontrol eder; hem anahtar hem yükselteçtir.'],
 ['Topraklama','Kaçak akıma en kolay yolu sunarak insan üzerinden geçmesini engeller.'],
 ['Güç Faktörü','Çekilen akımın ne kadarının gerçek işe dönüştüğünü gösterir; düşükse şebeke boşuna yorulur.'],
],
yazilim: [
 ['Algoritma','Bir problemi adım adım, belirsizlik bırakmadan çözen sonlu talimatlar dizisidir.'],
 ['Karmaşıklık','Bir algoritmanın maliyeti, veri büyüdükçe nasıl arttığıyla ölçülür; sabit hız yanıltıcıdır.'],
 ['İkili Arama','Sıralı bir listede her adımda yarıyı eleyerek arar; milyon kayıtta yirmi adım yeter.'],
 ['Veri Yapısı','Doğru veri yapısı seçmek, çoğu zaman daha zeki bir algoritmadan daha çok hız kazandırır.'],
 ['Özyineleme','Fonksiyonun kendini çağırmasıdır; mutlaka bir durma koşulu gerekir.'],
 ['Sürüm Kontrolü','Kodun geçmişini saklar; hangi satırın ne zaman ve neden değiştiğini geri izlemeni sağlar.'],
 ['Test','Otomatik test, kodun ilerideki değişikliklerde bozulmadığını kanıtlayan güvenlik ağıdır.'],
 ['Hata Ayıklama','Hatanın yerini tahmin etmek yerine daraltmak esastır; her adımda arama alanını yarıya indir.'],
 ['Önbellek','Sık kullanılan sonucu saklamak, yeniden hesaplamaktan kat kat ucuzdur.'],
 ['API','İki yazılımın birbiriyle konuşmak için üzerinde anlaştığı sözleşmedir.'],
 ['Teknik Borç','Hızlı çözüm bugün zaman kazandırır ama faiziyle geri ödenir.'],
 ['Eşzamanlılık','Aynı anda çalışan işler paylaşılan veriyi bozabilir; sıra ve kilit bu yüzden vardır.'],
],
yapayzeka: [
 ['Makine Öğrenmesi','Kural yazmak yerine, veriden örüntü çıkararak kuralı modele buldurmaktır.'],
 ['Eğitim Verisi','Model gördüğü veriyi öğrenir; veri taraflıysa sonuç da taraflı çıkar.'],
 ['Yapay Sinir Ağı','Basit birimlerin katmanlar hâlinde bağlanmasıyla karmaşık ilişkileri temsil eder.'],
 ['Ağırlık','Öğrenme, bağlantı ağırlıklarının hatayı azaltacak yönde küçük küçük güncellenmesidir.'],
 ['Aşırı Öğrenme','Model eğitim verisini ezberleyip yeni örneklerde başarısız olabilir.'],
 ['Doğrulama Kümesi','Modelin gerçek başarısı, hiç görmediği veriyle ölçülür.'],
 ['Gradyan İnişi','Hata yüzeyinde en dik iniş yönünde küçük adımlar atarak en aza yaklaşır.'],
 ['Öznitelik','Ham veriyi modelin anlayacağı anlamlı sayılara çevirmek başarının yarısıdır.'],
 ['Denetimsiz Öğrenme','Etiket olmadan verideki doğal kümeleri ve yapıyı bulmaya çalışır.'],
 ['Pekiştirmeli Öğrenme','Model deneyerek öğrenir; iyi sonuç ödül, kötü sonuç ceza olarak geri döner.'],
 ['Dil Modeli','Bir metinde sıradaki parçayı tahmin etmeyi öğrenerek dilin yapısını yakalar.'],
 ['Açıklanabilirlik','Bir modelin neden o kararı verdiğini gösterebilmek, doğru karar vermesi kadar önemlidir.'],
],
insaat: [
 ['Basınç ve Çekme','Beton basınca çok dayanıklı, çekmeye zayıftır; bu yüzden içine çelik konur.'],
 ['Betonarme','Beton ile çeliğin ısıl genleşmesi neredeyse aynıdır; bu uyum ikisini ortak çalıştırır.'],
 ['Kiriş','Yükü kolonlara aktarır; alt yüzeyi çekme, üst yüzeyi basınç altında çalışır.'],
 ['Kolon','Düşey yükü temele taşır; narinleştikçe burkulma riski hızla artar.'],
 ['Temel','Yapının yükünü zemine yayar; zemin etüdü yapılmadan atılan temel en pahalı hatadır.'],
 ['Deprem Yalıtımı','Bina ile temel arasına konan esnek yataklar, sarsıntının üst yapıya geçişini azaltır.'],
 ['Kesme Kuvveti','Kirişin mesnete yakın bölgeleri kesmeye zorlanır; etriye tam burada sıklaştırılır.'],
 ['Kemer','Yükü basınca çevirerek yayar; bu yüzden çekmeye zayıf taş bile kemerde çok güçlüdür.'],
 ['Kafes Sistem','Üçgenlerden oluşan taşıyıcı, az malzemeyle çok açıklık geçmeyi sağlar.'],
 ['Beton Kürü','Beton kurumaz, kimyasal olarak sertleşir; ilk günlerde nemli tutulmazsa dayanımı düşer.'],
 ['Yük Türleri','Ölü yük yapının kendisi, hareketli yük ise kullanıcı ve eşyadır; ikisi ayrı hesaplanır.'],
 ['Güvenlik Katsayısı','Tasarım her zaman beklenen yükün üzerine pay konularak yapılır; belirsizliğin bedeli budur.'],
],
mimarlik: [
 ['Ölçek','Mekânın büyüklüğü insan bedeniyle kıyaslandığında anlam kazanır; ölçek duyguyu belirler.'],
 ['Sirkülasyon','İnsanların bina içinde nasıl aktığı, planın en belirleyici kararıdır.'],
 ['Doğal Işık','Işığın yönü ve saati mekânın algısını değiştirir; kuzey ışığı sabit, güney ışığı serttir.'],
 ['Altın Oran','Yaklaşık 1,618 olan bu oran, birçok tarihi yapıda denge kurmak için kullanılmıştır.'],
 ['Boşluk','Mimarlıkta değerli olan çoğu zaman duvar değil, duvarların çevrelediği boşluktur.'],
 ['Yönlenme','Binanın güneşe ve rüzgâra göre çevrilmesi, ısıtma ve soğutma yükünü ciddi biçimde değiştirir.'],
 ['Malzeme Dokusu','Aynı biçim, farklı malzemeyle bambaşka bir mekân hissi verir.'],
 ['Modül','Tekrarlanan bir birim üzerinden tasarlamak, hem üretimi hem esnekliği kolaylaştırır.'],
 ['Erişilebilirlik','İyi tasarım, tekerlekli sandalyeden bebek arabasına herkesin aynı yolu kullanabilmesidir.'],
 ['Akustik','Sert ve paralel yüzeyler sesi çoğaltır; kırıcı ve emici yüzeyler konuşmayı anlaşılır kılar.'],
 ['Cephe','Cephe süs değil, iklim ile iç mekân arasındaki filtre olarak çalışır.'],
 ['Vaziyet Planı','Yapı araziye yerleşmeden önce, arazinin eğimi ve manzarası binayı biçimlendirir.'],
],
robotik: [
 ['Serbestlik Derecesi','Bir robot kolunun bağımsız hareket edebildiği eksen sayısıdır; insan kolu yedi eksene sahiptir.'],
 ['Aktüatör','Elektrik sinyalini harekete çeviren bileşendir; robotun kasıdır.'],
 ['Enkoder','Milin ne kadar döndüğünü sayar; robot konumunu bu geri besleme sayesinde bilir.'],
 ['Kapalı Çevrim','Sistem çıktısını ölçüp hedefle karşılaştırır ve farkı sürekli düzeltir.'],
 ['PID Kontrol','Hatanın anlık, birikmiş ve değişim hızına bakarak yumuşak ve kararlı hareket üretir.'],
 ['Ters Kinematik','Ucun gitmesi gereken noktadan yola çıkıp her eklemin açısını hesaplamaktır.'],
 ['Sensör Füzyonu','Tek sensör yanılır; birden fazla sensörün verisini birleştirmek konumu güvenilir kılar.'],
 ['SLAM','Robot haritayı çıkarırken aynı anda o haritada kendi yerini de bulur.'],
 ['Tutucu','Kavrama kuvveti çok azsa düşürür, çok fazlaysa kırar; ayar malzemeye göre yapılır.'],
 ['Güvenlik Alanı','İnsanla çalışan robotlar temas kuvvetini algılayıp anında durabilmelidir.'],
 ['Gecikme','Algılama ile tepki arasındaki süre büyüdükçe kontrol kararsızlaşır.'],
 ['Otonomi Seviyesi','Uzaktan kumandadan tam otonoma kadar kademeler vardır; her kademe farklı sorumluluk taşır.'],
],
otomotiv: [
 ['İçten Yanmalı Motor','Yakıt silindir içinde patlar, pistonu iter ve bu doğrusal hareket krankla dönmeye çevrilir.'],
 ['Dört Zaman','Emme, sıkıştırma, yanma ve egzoz adımları iki tam krank turunda tamamlanır.'],
 ['Sıkıştırma Oranı','Karışım ne kadar sıkışırsa verim o kadar artar; ama vuruntu sınırı aşılamaz.'],
 ['Turbo','Egzoz gazının enerjisiyle çalışan türbin, motora daha çok hava basarak gücü artırır.'],
 ['Şanzıman','Motorun dar verimli devir aralığını, tekerleğin geniş hız ihtiyacına uyarlar.'],
 ['Diferansiyel','Virajda dış tekerleğin iç tekerlekten daha hızlı dönmesine izin verir.'],
 ['Fren Sistemi','Frenleme, hareket enerjisini sürtünme yoluyla ısıya çevirmektir; ısınan fren zayıflar.'],
 ['ABS','Tekerlek kilitlenmeden hemen önce basıncı boşaltır; böylece direksiyon hâkimiyeti korunur.'],
 ['Süspansiyon','Yol darbelerini yutarken lastiğin zeminle temasını sürekli tutmakla görevlidir.'],
 ['Aerodinamik','Yüksek hızda tüketimin büyük kısmı hava direncine gider; gövde biçimi yakıt demektir.'],
 ['Elektrikli Aktarma','Elektrik motoru sıfır devirden itibaren tam tork verir; bu yüzden hızlanma çok keskindir.'],
 ['Rejeneratif Fren','Yavaşlarken motor jeneratöre dönüşür ve enerjinin bir kısmını bataryaya geri yazar.'],
],
});

Object.assign(KONULAR, {
denizcilik: [
 ['Suyun Kaldırma Kuvvetli','Bir cisim, taşırdığı suyun ağırlığı kadar yukarı itilir; gemiler bu yüzden çelik olsa da yüzer.'],
 ['Su Çekimi','Geminin su altında kalan derinliğidir; yük arttıkça artar ve limana girişi belirler.'],
 ['Metasantr','Yatan geminin doğrulma eğilimini belirleyen noktadır; düşük kalırsa gemi alabora olur.'],
 ['Safra Suyu','Boş gemi dengesini korumak için tanklara su alınır; bu su türlerin taşınmasına da yol açar.'],
 ['Pruva ve Kıç','Geminin ön tarafı pruva, arka tarafı kıçtır; iskele sol, sancak sağ anlamına gelir.'],
 ['Deniz Mili','Bir deniz mili 1852 metredir ve yeryüzünde bir açı dakikasına karşılık gelir.'],
 ['Knot','Saatte bir deniz mili hızdır; denizcilikte hız her zaman knot ile ölçülür.'],
 ['Rota ve Kerteriz','Rota geminin gittiği yön, kerteriz ise bir cismin gemiye göre görüldüğü yöndür.'],
 ['Pusula Sapması','Manyetik kuzey ile gerçek kuzey aynı değildir; fark bölgeye göre düzeltilir.'],
 ['Pervane Kavitasyonu','Pervane çok hızlı dönünce suda buhar kabarcıkları oluşur; patlayan kabarcıklar metali aşındırır.'],
 ['Gelgit','Ay ve Güneş’in çekimiyle deniz seviyesi düzenli yükselip alçalır; sığ limanlarda seyri belirler.'],
 ['Denge Dümeni','Yalpayı azaltan kanatlar gemiyi dengede tutar; konfor kadar güvenlik meselesidir.'],
],
endustri: [
 ['Darboğaz','Bir üretim hattının hızı, en yavaş istasyonun hızıdır; diğerlerini hızlandırmak işe yaramaz.'],
 ['Yalın Üretim','Müşteriye değer katmayan her adım israftır ve sistemden çıkarılmalıdır.'],
 ['Tam Zamanında','Malzeme ihtiyaç duyulduğu anda gelir; stok maliyeti düşer ama tedarik hassaslaşır.'],
 ['Kaizen','Büyük atılımlar yerine, herkesin katıldığı sürekli küçük iyileştirmelere dayanır.'],
 ['Kuyruk Teorisi','Kapasite doluluğa yaklaştıkça bekleme süresi doğrusal değil, patlayarak artar.'],
 ['Kanban','Üretimi tahminle değil, gerçek tüketim sinyaliyle tetikleyen görsel kart sistemidir.'],
 ['Çevrim Süresi','Bir ürünün hattan çıkma aralığıdır; müşteri talebine göre ayarlanır.'],
 ['İş Etüdü','Bir işin adımları ölçülüp gereksiz hareketler çıkarılarak süre kısaltılır.'],
 ['Ergonomi','İş insana uydurulur; yanlış yükseklikteki tezgâh üretkenliği de sağlığı da düşürür.'],
 ['Altı Sigma','Süreç değişkenliğini azaltarak hata oranını milyonda birkaç seviyesine indirmeyi hedefler.'],
 ['Tedarik Zinciri','Zincirin gücü en zayıf halkasına eşittir; tek kaynağa bağlılık en büyük risktir.'],
 ['Kırbaç Etkisi','Küçük talep dalgalanmaları zincirin üst halkalarında büyüyerek dev stok hatalarına dönüşür.'],
],
malzeme: [
 ['Gerilme-Şekil Değiştirme','Malzemenin yük altındaki davranışı bu eğriyle özetlenir; kopma noktası tasarımın sınırıdır.'],
 ['Elastik ve Plastik','Elastik bölgede yük kalkınca eski hâline döner, plastik bölgede kalıcı olarak biçim değiştirir.'],
 ['Sertlik','Yüzeyin çizilmeye ve girintiye karşı direncidir; dayanımdan farklı bir özelliktir.'],
 ['Tokluk','Kırılmadan önce yutabildiği enerjidir; cam sert ama toksuz, çelik hem sert hem toktur.'],
 ['Alaşım','Saf metale başka element eklemek kristal yapıyı bozar ve genellikle dayanımı artırır.'],
 ['Isıl İşlem','Isıtma ve soğutma hızları çeliğin iç yapısını, dolayısıyla sertliğini kökten değiştirir.'],
 ['Korozyon','Metal çevresiyle kimyasal tepkimeye girerek bozunur; paslanmaz çelik yüzeyinde koruyucu film oluşturur.'],
 ['Kompozit','Farklı iki malzeme birleşerek tek başlarına olmayan bir özellik kazanır; karbon fiber buna örnektir.'],
 ['Polimer','Uzun zincir moleküllerden oluşur; zincirlerin düzeni sertlik ve esnekliği belirler.'],
 ['Seramik','Basınca çok dayanıklı ve ısıya çok dirençlidir ama darbede ani kırılır.'],
 ['Camsı Geçiş','Polimerler belli bir sıcaklığın altında sertleşip kırılganlaşır; soğukta plastik çatlar.'],
 ['Nanomalzeme','Boyut nanometreye inince aynı madde farklı optik, elektriksel ve mekanik özellikler gösterir.'],
],
enerji: [
 ['Enerjinin Korunumu','Enerji üretilmez, yalnızca bir biçimden diğerine dönüştürülür.'],
 ['Verim Zinciri','Her dönüşüm adımında kayıp olur; toplam verim adımların çarpımıdır.'],
 ['Güneş Paneli','Fotonlar yarı iletkende elektron kopararak doğrudan elektrik akımı üretir.'],
 ['Rüzgâr Türbini','Rüzgârdan alınabilecek enerji hızın küpüyle artar; iki kat rüzgâr sekiz kat güç demektir.'],
 ['Hidroelektrik','Suyun yükseklik enerjisi türbini döndürür; depolanabilir olması en büyük avantajıdır.'],
 ['Nükleer Fisyon','Ağır çekirdek parçalanırken kütlenin küçük bir kısmı çok büyük enerjiye dönüşür.'],
 ['Batarya','Kimyasal enerjiyi elektriğe çevirir; kapasite kadar şarj-deşarj hızı da tasarım kısıtıdır.'],
 ['Şebeke Dengesi','Şebekede üretim ile tüketim her an eşit olmalıdır; fark frekansı kaydırır.'],
 ['Temel Yük','Sürekli çalışan kaynaklar temel yükü karşılar; ani talep artışını hızlı kaynaklar kapatır.'],
 ['Enerji Depolama','Yenilenebilir kaynaklar değişkendir; depolama olmadan şebekeye tam entegre olamazlar.'],
 ['Isı Pompası','Isı üretmez, var olan ısıyı taşır; bu yüzden verdiği ısı harcadığı elektrikten fazladır.'],
 ['Yalıtım','En ucuz enerji, hiç harcanmayan enerjidir; iyi yalıtım üretimden daha hızlı geri döner.'],
],
cevre: [
 ['Karbon Ayak İzi','Bir faaliyetin atmosfere saldığı sera gazının karbondioksit karşılığıdır.'],
 ['Sera Etkisi','Atmosferdeki bazı gazlar yeryüzünden yansıyan ısıyı tutar; bu olmasa Dünya çok soğuk olurdu.'],
 ['Su Döngüsü','Buharlaşma, yoğuşma ve yağış zinciri gezegendeki suyu sürekli yeniden dağıtır.'],
 ['Atık Su Arıtma','Katı ayırma, biyolojik parçalama ve dezenfeksiyon adımlarıyla su doğaya geri verilir.'],
 ['Biyolojik Oksijen İhtiyacı','Suyu temizleyen bakterilerin harcadığı oksijendir; yüksek değer ağır kirliliği gösterir.'],
 ['Ötrofikasyon','Fazla gübre suya karışınca yosun patlar, oksijen tükenir ve canlılar ölür.'],
 ['Geri Dönüşüm','Malzeme her döngüde bir miktar bozunur; azaltmak ve yeniden kullanmak daha etkilidir.'],
 ['Mikroplastik','Parçalanan plastikler beş milimetrenin altına iner ve besin zincirine girer.'],
 ['Hava Kalitesi','Partikül maddeler akciğerin derinine ulaşır; en tehlikelisi 2,5 mikron altındakilerdir.'],
 ['Yaşam Döngüsü Analizi','Bir ürünün etkisi, hammaddeden atığa kadar tüm zincir hesaplanarak ölçülür.'],
 ['Biyoçeşitlilik','Tür çeşitliliği azaldıkça ekosistem şoklara karşı dayanıksızlaşır.'],
 ['Döngüsel Ekonomi','Al-kullan-at yerine, atığı yeniden kaynak yapan kapalı bir döngü hedeflenir.'],
],
tip: [
 ['Anamnez','Doğru teşhisin büyük kısmı hastanın hikâyesini dikkatle dinlemekten çıkar.'],
 ['Vital Bulgular','Nabız, tansiyon, solunum, ateş ve oksijen doygunluğu hastanın anlık durum özetidir.'],
 ['Ayırıcı Tanı','Belirtiyle uyuşan tüm olasılıklar listelenir, sonra teker teker elenir.'],
 ['Enfeksiyon','Bakteri, virüs, mantar ve parazit farklı tedaviler gerektirir; ayrımı yapmadan ilaç verilmez.'],
 ['Antibiyotik Direnci','Gereksiz kullanım dirençli suşları seçer; ilaç zamanla etkisiz kalır.'],
 ['Bağışıklık Belleği','Vücut karşılaştığı etkeni hatırlar; aşının çalışma ilkesi budur.'],
 ['İltihap','Kızarıklık, ısı, şişlik ve ağrı; bağışıklığın bölgeye yaptığı savunma hamlesidir.'],
 ['Ateş','Ateş hastalık değil savunmadır; çoğu mikrop yüksek sıcaklıkta zorlanır.'],
 ['Plasebo Etkisi','Etkisiz bir uygulama bile beklenti nedeniyle iyileşme yaratabilir; bu yüzden çalışmalar kör yapılır.'],
 ['Kanıta Dayalı Tıp','Karar, kişisel deneyimle değil, iyi tasarlanmış çalışmaların bulgularıyla verilir.'],
 ['Yan Etki','Her etkili ilacın istenmeyen etkisi de vardır; tedavi fayda-zarar dengesidir.'],
 ['Kronik Hastalık','Uzun süreli hastalıklarda amaç tam kür değil, ilerlemeyi yavaşlatıp yaşam kalitesini korumaktır.'],
],
cerrahi: [
 ['Asepsi','Ameliyat alanına mikrop girmesini önlemek, en kritik ve en görünmez adımdır.'],
 ['İnsizyon','Kesi yeri; iyileşme, iz ve erişim kolaylığı düşünülerek önceden planlanır.'],
 ['Hemostaz','Kanamanın kontrolü, görüş alanını temiz tutar ve ameliyatın seyrini belirler.'],
 ['Sütur','Dikiş tekniği ve iplik seçimi, yaranın ne kadar sağlam ve ne kadar izsiz kapanacağını değiştirir.'],
 ['Anestezi','Genel anestezi bilinci, lokal anestezi yalnız bölgeyi kapatır; seçim işleme göre yapılır.'],
 ['Laparoskopi','Küçük deliklerden kamera ve alet girer; iyileşme süresi açık ameliyata göre çok kısalır.'],
 ['Anatomik Varyasyon','Her hastanın damar ve sinir düzeni kitaptaki gibi olmaz; cerrah buna hazır olmalıdır.'],
 ['El Titremesi','Mikro cerrahide milimetrenin altındaki titreme bile kritiktir; destek ve duruş bunu azaltır.'],
 ['Ameliyat Kontrol Listesi','Basit bir liste, yanlış taraf ve unutulan malzeme hatalarını belirgin biçimde düşürür.'],
 ['Doku İyileşmesi','Yara pıhtı, iltihap, yeni doku ve olgunlaşma evrelerinden geçer; her evrenin süresi vardır.'],
 ['Enfeksiyon Riski','Ameliyat süresi uzadıkça enfeksiyon olasılığı artar; hız da bir güvenlik unsurudur.'],
 ['Post-op Takip','Ameliyat biter ama tedavi bitmez; ilk saatlerdeki bulgular komplikasyonu erken yakalar.'],
],
kardiyo: [
 ['Kalbin Odacıkları','İki kulakçık ve iki karıncık vardır; sağ taraf akciğere, sol taraf tüm vücuda pompalar.'],
 ['Kalp Kapakları','Kapaklar kanın tek yönde akmasını sağlar; kaçak ya da darlık yükü artırır.'],
 ['Sistol ve Diyastol','Sistol kasılma, diyastol gevşeme evresidir; tansiyonun iki değeri bunlara karşılık gelir.'],
 ['Sinüs Düğümü','Kalbin doğal pili buradadır; ritmi kendi başlatır ve yayar.'],
 ['EKG','Kalbin elektriksel etkinliğini kaydeder; ritim ve iskemi hakkında hızlı bilgi verir.'],
 ['Ateroskleroz','Damar duvarında plak birikir, damar daralır ve kan akışı kısıtlanır.'],
 ['Miyokart İnfarktüsü','Damar tıkanınca kalp kası oksijensiz kalır; her dakika kaybedilen doku artar.'],
 ['Kalp Yetmezliği','Kalp yeterince pompalayamaz; nefes darlığı ve ödem en tipik bulgulardır.'],
 ['Atriyal Fibrilasyon','Kulakçıklar düzensiz titrer; pıhtı oluşma ve inme riski yükselir.'],
 ['Kan Basıncı','Yüksek tansiyon uzun süre belirti vermez ama damarları sessizce yıpratır.'],
 ['Kolesterol','LDL damar duvarında birikir, HDL ise geri taşır; oran tek başına toplam değerden anlamlıdır.'],
 ['Kardiyak Rehabilitasyon','Kontrollü egzersiz, kalp olayı sonrası dayanıklılığı ve yaşam süresini artırır.'],
],
noroloji: [
 ['Nöron','Sinir hücresi, dendritlerinden sinyal alır ve aksonu boyunca ileri iletir.'],
 ['Aksiyon Potansiyeli','Sinyal, zar boyunca ilerleyen ani bir elektriksel dalga olarak taşınır.'],
 ['Sinaps','İki nöron arasındaki boşlukta iletim kimyasal ileticilerle sağlanır.'],
 ['Miyelin','Aksonu saran yalıtım kılıfı iletim hızını kat kat artırır; hasarında sinyal yavaşlar.'],
 ['Nöroplastisite','Beyin kullanıma göre bağlantılarını yeniden düzenler; öğrenme fiziksel bir değişimdir.'],
 ['Beyin Lobları','Frontal karar, parietal duyu, temporal işitme ve bellek, oksipital görme ile ilişkilidir.'],
 ['Serebellum','Beyincik dengeyi ve hareketin ince ayarını yönetir; hasarında hareket bozulur.'],
 ['Refleks Yayı','Bazı tepkiler beyne uğramadan omurilikte kapanır; bu yüzden çok hızlıdır.'],
 ['Kan-Beyin Bariyeri','Beyni koruyan seçici bir sınırdır; birçok ilaç bu yüzden beyne geçemez.'],
 ['İnme','Damar tıkanır ya da yırtılır; zamanla kaybedilen nöron sayısı hızla artar.'],
 ['Epilepsi','Nöron gruplarının eşzamanlı aşırı deşarjı nöbete yol açar.'],
 ['Nörotransmitter','Dopamin, serotonin ve GABA gibi iletiler ruh hâlini, hareketi ve uyanıklığı düzenler.'],
],
dis: [
 ['Mine','Vücudun en sert dokusudur ama bir kez kaybedilince yeniden üretilmez.'],
 ['Dentin','Minenin altındaki daha yumuşak katmandır; açığa çıkınca hassasiyet başlar.'],
 ['Pulpa','Dişin içindeki damar ve sinir dokusudur; iltihaplanınca şiddetli ağrı yapar.'],
 ['Plak','Bakteri filmi diş yüzeyinde birikir; temizlenmezse sertleşip tartara döner.'],
 ['Çürük','Bakteriler şekeri aside çevirir, asit mineyi çözer; süreç yavaş ama süreklidir.'],
 ['Florür','Mine yapısını güçlendirir ve asit çözünmesine karşı direnci artırır.'],
 ['Diş Eti Hastalığı','Kanayan diş eti erken uyarıdır; ilerlerse dişi tutan kemik erir.'],
 ['Kanal Tedavisi','Enfekte pulpa temizlenip boşluk doldurulur; diş çekilmeden korunur.'],
 ['Dolgu','Çürük temizlendikten sonra boşluk doldurulur; kenar uyumu yeni çürüğü önler.'],
 ['Kapanış','Alt ve üst dişlerin temas düzeni; bozulursa çene eklemi ve kaslar zorlanır.'],
 ['Yirmi Yaş Dişi','Çenede yer kalmadığında gömülü kalır ve komşu dişe baskı yapabilir.'],
 ['Fırçalama Tekniği','Süre ve açı, fırçanın sertliğinden önemlidir; diş eti sınırı 45 derecede temizlenir.'],
],
});

Object.assign(KONULAR, {
eczacilik: [
 ['Etken Madde','İlacın işi yapan bileşenidir; geri kalanı taşıyıcı ve yardımcı maddelerdir.'],
 ['Doz','Aynı madde dozuna göre ilaç ya da zehir olur; doz-yanıt ilişkisi eczacılığın temelidir.'],
 ['Yarılanma Ömrü','İlacın kandaki miktarının yarıya inme süresidir; kullanım aralığını bu belirler.'],
 ['Emilim','İlacın kana geçme hızı; aç ya da tok alınması etkiyi belirgin biçimde değiştirebilir.'],
 ['İlk Geçiş Etkisi','Ağızdan alınan ilaç önce karaciğerden geçer ve bir kısmı daha kana ulaşmadan parçalanır.'],
 ['Biyoyararlanım','Alınan dozun ne kadarının etkin biçimde kana ulaştığını gösterir.'],
 ['İlaç Etkileşimi','İki ilaç birbirinin etkisini artırabilir ya da yok edebilir; liste her zaman kontrol edilir.'],
 ['Kontrollü Salım','Kaplama sayesinde etken madde saatler boyunca yavaşça salınır.'],
 ['Jenerik İlaç','Aynı etken maddeyi aynı biyoyararlanımla taşır; patent süresi bitince üretilir.'],
 ['Saklama Koşulu','Isı ve ışık birçok etken maddeyi bozar; yanlış saklanan ilaç etkisizleşir.'],
 ['Antagonist ve Agonist','Agonist reseptörü uyarır, antagonist ise bağlanıp uyarılmasını engeller.'],
 ['Farmakovijilans','İlaç piyasaya çıktıktan sonra da yan etkiler toplanır; nadir etkiler ancak böyle görülür.'],
],
beslenme: [
 ['Makro Besinler','Karbonhidrat, protein ve yağ enerji sağlayan üç ana gruptur.'],
 ['Kalori Dengesi','Alınan ve harcanan enerji farkı kilo değişiminin temel belirleyicisidir.'],
 ['Protein İhtiyacı','Kas onarımı için gereklidir; hareketli kişilerde ihtiyaç kilogram başına belirgin artar.'],
 ['Tam Protein','Tüm temel amino asitleri içerir; bitkisel kaynaklar birleştirilerek tamamlanabilir.'],
 ['Lif','Sindirilmez ama tokluk verir, kan şekerini yavaşlatır ve bağırsak florasını besler.'],
 ['Glisemik İndeks','Bir gıdanın kan şekerini ne kadar hızlı yükselttiğini gösterir.'],
 ['Doymuş ve Doymamış Yağ','Yağ kötü değildir; türü ve miktarı damar sağlığı için belirleyicidir.'],
 ['Mikro Besinler','Vitamin ve mineraller enerji vermez ama enzim sistemlerinin çalışması için şarttır.'],
 ['Su Dengesi','Hafif susuzluk bile performansı ve dikkati ölçülebilir biçimde düşürür.'],
 ['Öğün Zamanlaması','Toplam alım en belirleyicidir; zamanlama sporcularda toparlanmayı etkiler.'],
 ['Besin Yoğunluğu','Aynı kaloride çok daha fazla besin sunan gıdalar tercih edilir.'],
 ['Etiket Okuma','İçindekiler miktara göre sıralanır; ilk üç madde ürünün gerçek yapısını anlatır.'],
],
fizyo: [
 ['Hareket Açıklığı','Bir eklemin gidebildiği açıdır; kısıtlanınca çevre eklemler telafi etmeye çalışır.'],
 ['Kas Kısalığı','Uzun süre kısa kalan kas gerilir; duruş bozukluklarının büyük kısmı buradan gelir.'],
 ['Propriyosepsiyon','Vücudun kendi konumunu hissetme duyusudur; yaralanma sonrası ilk bozulan budur.'],
 ['İzometrik Kasılma','Kas boyu değişmeden kuvvet üretir; ağrılı dönemde güvenli bir başlangıçtır.'],
 ['Eksantrik Çalışma','Kas uzarken yük taşır; tendon iyileşmesinde en etkili yöntemlerden biridir.'],
 ['Manuel Terapi','Elle uygulanan mobilizasyon eklem hareketini ve dolaşımı artırır.'],
 ['Soğuk ve Sıcak','Akut dönemde soğuk şişliği azaltır, kronik dönemde sıcak dolaşımı ve esnekliği artırır.'],
 ['Kademeli Yükleme','Doku yükü yavaş yavaş artırılarak güçlenir; ani artış yeniden sakatlık getirir.'],
 ['Ağrı Kapı Kontrolü','Dokunma ve titreşim uyarıları ağrı sinyalinin iletimini kısmen bastırır.'],
 ['Yürüyüş Analizi','Adımın her evresi incelenir; küçük bir asimetri uzun vadede eklem aşındırır.'],
 ['Core Stabilitesi','Gövde derin kasları omurgayı sabitler; kol ve bacak gücü bu zemine dayanır.'],
 ['Egzersiz Uyumu','En iyi program uygulanan programdır; basit ve kısa reçeteler daha çok sürdürülür.'],
],
veteriner: [
 ['Tür Farkı','Bir türde güvenli ilaç diğerinde zehirli olabilir; kedilerde parasetamol buna örnektir.'],
 ['Vital Değerler','Her türün normal nabız ve solunum aralığı farklıdır; değerlendirme türe göre yapılır.'],
 ['Zoonoz','Hayvandan insana geçebilen hastalıklardır; kuduz ve bruselloz en bilinenlerindendir.'],
 ['Aşı Takvimi','Yavru hayvanlarda anneden gelen bağışıklık azaldıkça aşı koruması devreye girer.'],
 ['Parazit Kontrolü','İç ve dış parazitler düzenli aralıklarla, tartılan ağırlığa göre tedavi edilir.'],
 ['Beden Kondisyon Skoru','Hayvanın zayıflık ve şişmanlık düzeyi elle muayeneyle puanlanır.'],
 ['Davranış Okuma','Kulak, kuyruk ve duruş; ağrının ve stresin en erken göstergeleridir.'],
 ['Ruminant Sindirimi','Geviş getirenlerde dört bölmeli mide selülozu bakteriler yardımıyla parçalar.'],
 ['Sürü Sağlığı','Çiftlik hayvanlarında birey değil sürü izlenir; erken uyarı toplu kayıpları önler.'],
 ['Anestezi Riski','Küçük hayvanlarda ısı kaybı hızlıdır; ameliyat sırasında sıcaklık takibi kritiktir.'],
 ['Kısırlaştırma','Popülasyon kontrolü sağlar ve bazı üreme sistemi hastalıklarının riskini düşürür.'],
 ['Kuş ve Sürüngen','Egzotik türlerde belirti çok geç görünür; hasta göründüğünde hastalık ilerlemiştir.'],
],
psikoloji: [
 ['Bilişsel Çarpıtma','Zihin gerçeği kısayollarla işler; felaketleştirme ve genelleme en yaygınlarıdır.'],
 ['Koşullanma','Bir uyaran, tekrar eden eşleşmeyle tepkiyi kendi başına tetikler hâle gelir.'],
 ['Pekiştirme','Davranışın ardından gelen sonuç, o davranışın tekrar etme olasılığını belirler.'],
 ['Çalışma Belleği','Aynı anda tutabildiğimiz bilgi miktarı sınırlıdır; genelde birkaç birimdir.'],
 ['Bağlanma Kuramı','Erken dönemdeki bakım ilişkisi, yetişkinlikteki ilişki örüntülerini etkiler.'],
 ['Bilişsel Çelişki','Davranış ile inanç uyuşmayınca rahatsızlık doğar; genelde inanç değiştirilerek çözülür.'],
 ['Onay Yanlılığı','İnsan, inandığını destekleyen bilgiyi arar ve çelişeni fark etmez.'],
 ['Stres Tepkisi','Beden tehdit algıladığında savaş, kaç ya da donma tepkilerinden birini verir.'],
 ['Kaygı ve Kaçınma','Kaçınmak kaygıyı kısa vadede azaltır ama uzun vadede büyütür.'],
 ['Maruz Bırakma','Kontrollü ve kademeli karşılaşma, korkunun sönmesini sağlayan en kanıtlı yöntemdir.'],
 ['Motivasyon','İçsel motivasyon dışsal ödülden daha uzun sürer; ödül bazen içsel isteği zayıflatır.'],
 ['Terapötik İlişki','Tedavinin başarısında yöntemden çok, kurulan güven ilişkisi belirleyicidir.'],
],
acil: [
 ['ABC Sırası','Önce hava yolu, sonra solunum, sonra dolaşım; sıra hayat kurtarır.'],
 ['Triyaj','Sınırlı kaynakta önce en çok fayda görecek hasta değerlendirilir.'],
 ['Altın Saat','Ağır travmada ilk saat içinde yapılan müdahale sağkalımı belirgin artırır.'],
 ['CPR','Kesintisiz ve derin göğüs basısı, beyne kan gitmesini sürdüren temel işlemdir.'],
 ['Defibrilasyon','Bazı ritim bozukluklarında elektrik şoku kalbin kendi ritmini yeniden başlatır.'],
 ['Glasgow Koma Skalası','Göz, sözel ve motor yanıt puanlanarak bilinç düzeyi ortak bir dille ifade edilir.'],
 ['Şok','Doku perfüzyonunun yetersizliğidir; tansiyon düşmeden önce nabız hızlanır.'],
 ['Kanama Kontrolü','Doğrudan bası ilk adımdır; turnike yalnızca kontrol edilemeyen uzuv kanamasında kullanılır.'],
 ['Hipotermi','Travma hastasında soğuma pıhtılaşmayı bozar; hasta örtülerek ısı korunur.'],
 ['İlaç Hatası','Doğru hasta, doğru ilaç, doğru doz, doğru yol ve doğru zaman her seferinde kontrol edilir.'],
 ['Devir Teslim','Vardiya değişiminde yapılandırılmış aktarım, en sık hata kaynağını ortadan kaldırır.'],
 ['Ekip İletişimi','Kapalı döngü iletişimde verilen talimat tekrar edilerek doğrulanır.'],
],
radyoloji: [
 ['Röntgen','X ışını yoğun dokulardan az geçer; kemik beyaz, hava siyah görünür.'],
 ['Kontrast Madde','Damar ya da organ boşluğunu doldurarak yumuşak dokuları ayırt edilir kılar.'],
 ['Bilgisayarlı Tomografi','Çok sayıda kesit birleştirilerek üç boyutlu görüntü oluşturulur.'],
 ['MR','Manyetik alan ve radyo dalgalarıyla çalışır; iyonlaştırıcı ışın içermez.'],
 ['Ultrason','Ses dalgalarının yankısını kullanır; gerçek zamanlı ve radyasyonsuzdur.'],
 ['Radyasyon Dozu','Gerekli olmayan görüntüleme yapılmaz; doz mümkün olan en düşük düzeyde tutulur.'],
 ['Artefakt','Hareket ve metal, görüntüde gerçekte olmayan görüntüler oluşturur.'],
 ['Pencereleme','Aynı veri farklı gri aralıklarla gösterilerek kemik ya da yumuşak doku öne çıkarılır.'],
 ['Anatomik Düzlem','Aksiyel, koronal ve sagital düzlemler görüntünün hangi yönden kesildiğini belirtir.'],
 ['Karşılaştırmalı Okuma','Eski tetkiklerle karşılaştırma, tek bir görüntüden çok daha fazla bilgi verir.'],
 ['Yanlış Pozitif','Her gölge hastalık değildir; gereksiz tetkik zinciri hastaya zarar verebilir.'],
 ['Girişimsel Radyoloji','Görüntü rehberliğinde iğne ve kateterle ameliyatsız tedavi yapılır.'],
],
fizik: [
 ['Newton’ın 1. Yasası','Bir cisim, üzerine net kuvvet etkimedikçe hareket durumunu korur.'],
 ['Newton’ın 2. Yasası','Kuvvet, kütle ile ivmenin çarpımına eşittir; aynı kuvvet ağır cismi az ivmelendirir.'],
 ['Etki-Tepki','Her kuvvete eşit ve zıt bir tepki vardır; roket tam olarak böyle ilerler.'],
 ['Momentum','Kütle ile hızın çarpımıdır ve çarpışmalarda toplamı korunur.'],
 ['Enerji Korunumu','Potansiyel ve kinetik enerji birbirine dönüşür; sürtünme yoksa toplam sabit kalır.'],
 ['Eğik Atış','Yatay hız sabit kalır, düşey hız yerçekimiyle değişir; en uzak menzil 45 derecede olur.'],
 ['Merkezcil Kuvvet','Dairesel harekette cismi merkeze doğru çeken kuvvet olmazsa cisim teğet doğrultuda savrulur.'],
 ['Sürtünme','Hareketi engeller ama yürümeyi de mümkün kılar; statik sürtünme kinetikten büyüktür.'],
 ['Dalga','Frekans ile dalga boyunun çarpımı hızı verir; ortam değişince hız da değişir.'],
 ['Doppler Etkisi','Yaklaşan kaynağın sesi tizleşir, uzaklaşanınki kalınlaşır.'],
 ['Entropi','Kapalı sistemlerde düzensizlik artma eğilimindedir; zamanın yönünü bu belirler.'],
 ['Görelilik','Işık hızı herkes için aynıdır; bu yüzden hızlı hareket edenin zamanı yavaşlar.'],
],
kimya: [
 ['Atom','Çekirdekte proton ve nötron, çevresinde elektron bulunur; kimlik proton sayısıyla belirlenir.'],
 ['Periyodik Tablo','Elementler artan proton sayısına göre dizilir; aynı sütun benzer kimyasal davranış gösterir.'],
 ['Kovalent Bağ','Atomlar elektron paylaşır; su ve organik moleküllerin temel bağıdır.'],
 ['İyonik Bağ','Bir atom elektron verir, diğeri alır; oluşan zıt yükler birbirini çeker.'],
 ['Mol','Bir moldeki tanecik sayısı Avogadro sayısı kadardır; kimyanın sayma birimidir.'],
 ['Denge','Tepkime ileri ve geri aynı hızda gidince derişimler sabitlenir, tepkime durmaz.'],
 ['Le Chatelier','Dengedeki sisteme yapılan etkiye sistem, etkiyi azaltacak yönde tepki verir.'],
 ['pH','Hidrojen iyonu derişiminin ölçüsüdür; her birim değişim on kat fark demektir.'],
 ['Katalizör','Tepkimeyi hızlandırır ama kendisi tükenmez; aktivasyon enerjisini düşürür.'],
 ['Ekzotermik ve Endotermik','Bazı tepkimeler ısı verir, bazıları ısı çeker; işaret enerji yönünü gösterir.'],
 ['Oksidasyon','Elektron kaybıdır; paslanma ve yanma aynı temel süreci paylaşır.'],
 ['Organik Kimya','Karbon dört bağ yapabildiği için sonsuz çeşitlilikte zincir ve halka kurabilir.'],
],
biyoloji: [
 ['Hücre','Yaşamın en küçük bağımsız birimidir; her hücre başka bir hücreden gelir.'],
 ['Mitokondri','Hücrenin enerji santralidir ve kendi DNA’sını taşır; anneden aktarılır.'],
 ['DNA','Dört bazın dizilimi, proteinlerin yapım talimatını kodlar.'],
 ['Protein Sentezi','DNA’dan kopyalanan RNA, ribozomda amino asit zincirine çevrilir.'],
 ['Mitoz','Hücre kendini kopyalar; oluşan iki hücre genetik olarak aynıdır.'],
 ['Mayoz','Üreme hücrelerinde kromozom sayısı yarıya iner ve karışım yeni çeşitlilik yaratır.'],
 ['Fotosentez','Bitkiler ışık enerjisiyle karbondioksit ve sudan şeker üretir, oksijeni salar.'],
 ['Solunum','Hücre şekeri oksijenle parçalayarak kullanılabilir enerjiye çevirir.'],
 ['Homeostazi','Canlı, iç dengesini dış koşullar değişse bile dar bir aralıkta tutar.'],
 ['Doğal Seçilim','Ortama daha uygun bireyler daha çok üreyerek özelliklerini yayar.'],
 ['Ekosistem','Enerji güneşten girer ve besin zincirinde her basamakta büyük ölçüde kaybolur.'],
 ['Mikrobiyota','Vücuttaki bakteri toplulukları sindirimden bağışıklığa kadar birçok süreci etkiler.'],
],
});

Object.assign(KONULAR, {
matematik: [
 ['Asal Sayı','Yalnızca bire ve kendine bölünen sayılardır; sonsuz tanedir ve şifrelemenin temelidir.'],
 ['Pisagor Bağıntısı','Dik üçgende hipotenüsün karesi, dik kenarların karelerinin toplamına eşittir.'],
 ['Pi Sayısı','Her çemberin çevresinin çapına oranı aynıdır ve yaklaşık 3,14159’dur.'],
 ['Türev','Bir büyüklüğün anlık değişim hızıdır; grafikte teğetin eğimine karşılık gelir.'],
 ['İntegral','Değişimi toplayarak birikmiş miktarı verir; eğri altındaki alandır.'],
 ['Fonksiyon','Her girdiye tek bir çıktı eşleyen kuraldır; matematiğin ortak dilidir.'],
 ['Logaritma','Bir sayıyı elde etmek için tabanın kaçıncı kuvvetinin gerektiğini söyler.'],
 ['Olasılık','Bir olayın gerçekleşme oranıdır; bağımsız olaylarda olasılıklar çarpılır.'],
 ['Normal Dağılım','Doğadaki birçok ölçüm ortalamanın çevresinde çan eğrisi biçiminde toplanır.'],
 ['Matris','Sayı tablolarıyla dönüşümleri temsil eder; grafikten yapay zekâya kadar kullanılır.'],
 ['Sonsuzluk','Bazı sonsuzluklar diğerlerinden büyüktür; gerçel sayılar doğal sayılardan daha kalabalıktır.'],
 ['İspat','Bir örnek yeterli değildir; matematikte iddia ancak genel bir kanıtla doğrulanır.'],
],
jeoloji: [
 ['Levha Tektoniği','Yer kabuğu büyük parçalara ayrılmıştır ve bu levhalar yılda birkaç santimetre hareket eder.'],
 ['Deprem','Levhalar arasında biriken gerilme aniden boşalır ve enerji dalgalar hâlinde yayılır.'],
 ['Fay Hattı','Kayaçların kırılıp göreli hareket ettiği kırık düzlemidir.'],
 ['Magma ve Lav','Yer altındaki erimiş kayaya magma, yüzeye çıkanına lav denir.'],
 ['Kayaç Döngüsü','Magmatik, tortul ve başkalaşım kayaçları zamanla birbirine dönüşür.'],
 ['Tortul Katmanlar','Alt katman genelde daha eskidir; bu ilke yer tarihinin okunmasını sağlar.'],
 ['Fosil','Tortul kayaçlarda korunan canlı izleri, katmanların yaşını belirlemede kullanılır.'],
 ['Radyometrik Yaş','Radyoaktif bozunma hızı bilindiği için kayacın yaşı hesaplanabilir.'],
 ['Erozyon','Su, rüzgâr ve buz yüzeyi aşındırır; jeolojik zamanda dağları düzleştirir.'],
 ['Yeraltı Suyu','Gözenekli katmanlarda biriken su, akiferler aracılığıyla yavaşça hareket eder.'],
 ['Mineral','Belirli kimyasal bileşimi ve kristal yapısı olan doğal katıdır; kayaçlar minerallerden oluşur.'],
 ['Volkanizma','Volkan türü magmanın akışkanlığına bağlıdır; koyu magma daha patlayıcıdır.'],
],
meteoroloji: [
 ['Basınç Alanı','Alçak basınçta hava yükselir ve bulut oluşur; yüksek basınçta hava alçalır ve gökyüzü açılır.'],
 ['Cephe','Farklı sıcaklıktaki hava kütlelerinin sınırıdır; en sert hava olayları burada oluşur.'],
 ['Nem','Bağıl nem, havanın taşıyabileceği en fazla su buharına göre yüzdedir.'],
 ['Çiy Noktası','Havanın soğutulduğunda yoğuşmaya başladığı sıcaklıktır; sisin habercisidir.'],
 ['Bulut Türleri','Kümülüs dikey gelişir, stratüs tabaka oluşturur, sirrus buz kristallerinden yapılır.'],
 ['Yağış Oluşumu','Damlacıklar birleşerek ağırlaşır ve yükselen hava akımı onları taşıyamayınca düşer.'],
 ['Rüzgâr','Hava basınç farkını dengelemek için yüksekten alçağa doğru hareket eder.'],
 ['Coriolis Etkisi','Dünya’nın dönüşü, hareket eden hava kütlelerini kuzey yarımkürede sağa saptırır.'],
 ['Jet Akımı','Yüksek irtifadaki hızlı hava nehri, hava sistemlerinin rotasını belirler.'],
 ['Radar','Yağmur damlalarından yansıyan sinyal, yağışın yerini ve şiddetini gösterir.'],
 ['Sayısal Tahmin','Atmosfer denklemleri süper bilgisayarda çözülür; küçük ölçüm hatası günler sonra büyür.'],
 ['İklim ve Hava','Hava günlük durumdur, iklim ise uzun yılların istatistiksel ortalamasıdır.'],
],
okyanus: [
 ['Termoklin','Sıcak yüzey suyu ile soğuk derin su arasındaki keskin sıcaklık geçiş katmanıdır.'],
 ['Tuzluluk','Ortalama binde 35’tir; buharlaşma artırır, nehir ağızları ve yağış azaltır.'],
 ['Okyanus Akıntıları','Rüzgâr ve yoğunluk farkı devasa su kütlelerini taşır; iklimi doğrudan etkiler.'],
 ['Termohalin Dolaşım','Sıcaklık ve tuzluluk farkı, okyanusları yavaş ama küresel bir konveyöre dönüştürür.'],
 ['Basınç','Her 10 metre derinlikte basınç bir atmosfer artar; dalış planı buna göre yapılır.'],
 ['Işık Bölgeleri','Fotosentez yalnız üst yüzlerce metrede olur; altta sürekli karanlık hüküm sürer.'],
 ['Plankton','Okyanusun üretim temelidir ve atmosferik oksijenin büyük bölümünü sağlar.'],
 ['Mercan Ağarması','Su ısınınca mercan ortak yaşadığı algleri atar ve beyazlaşarak zayıflar.'],
 ['Okyanus Asitlenmesi','Fazla karbondioksit suda çözünür ve pH düşürerek kabuklu canlıları zorlar.'],
 ['Sonar','Ses dalgasının yankı süresi ölçülerek derinlik ve cisimler haritalanır.'],
 ['Hidrotermal Bacalar','Derinlikte sıcak mineralli su fışkırır; güneş olmadan kemosentezle beslenen ekosistemler oluşur.'],
 ['Deniz Kirliliği','Plastikler akıntılarla toplanır ve okyanus ortasında geniş birikim alanları oluşturur.'],
],
genetik: [
 ['Gen','DNA üzerinde bir proteinin ya da işlevin tarifini taşıyan bölümdür.'],
 ['Kromozom','İnsanda 23 çift bulunur; biri anneden, biri babadan gelir.'],
 ['Alel','Aynı genin farklı versiyonlarıdır; baskın ve çekinik olarak davranabilirler.'],
 ['Genotip ve Fenotip','Genotip taşınan bilgidir, fenotip ise gözlenen özelliktir; çevre ikisinin arasına girer.'],
 ['Mutasyon','DNA dizisindeki değişikliktir; çoğu etkisizdir, bazıları zararlı, bazıları avantajlıdır.'],
 ['Kalıtım Kalıpları','Bazı hastalıklar baskın, bazıları çekinik, bazıları cinsiyete bağlı geçer.'],
 ['Taşıyıcılık','Çekinik bir aleli taşıyan kişi hasta olmaz ama çocuğuna aktarabilir.'],
 ['Epigenetik','Dizi değişmeden gen ifadesi açılıp kapanabilir; çevre bu anahtarları etkiler.'],
 ['PCR','Az miktardaki DNA parçası milyonlarca kez çoğaltılarak incelenebilir hâle getirilir.'],
 ['Dizileme','DNA’nın baz sırasının okunmasıdır; maliyeti yıllar içinde çarpıcı biçimde düştü.'],
 ['CRISPR','Belirli bir DNA dizisini hedefleyip kesmeye izin veren düzenleme aracıdır.'],
 ['Genetik Danışmanlık','Test sonucu tek başına karar vermez; risk, aile öyküsüyle birlikte yorumlanır.'],
],
ziraat: [
 ['Toprak Yapısı','Kum, kil ve silt oranı suyu tutma ve havalanma dengesini belirler.'],
 ['Toprak pH','Bitki besinlerinin alınabilirliği pH’a bağlıdır; yanlış pH gübreyi işe yaramaz kılar.'],
 ['NPK','Azot yaprak, fosfor kök ve çiçek, potasyum meyve ve dayanıklılık için gereklidir.'],
 ['Ekim Nöbeti','Aynı ürünü aynı tarlada tekrarlamak toprağı yorar ve hastalığı çoğaltır.'],
 ['Nadas','Toprağın bir sezon dinlendirilmesi nem ve besin biriktirmesini sağlar.'],
 ['Damla Sulama','Su doğrudan köke verilir; buharlaşma kaybı ve yabancı ot belirgin azalır.'],
 ['Tozlaşma','Birçok üründe verim, arı gibi tozlayıcıların varlığına doğrudan bağlıdır.'],
 ['Zararlı Yönetimi','Önce izleme ve kültürel önlem, en son kimyasal; direnç gelişimini bu sıra yavaşlatır.'],
 ['Kompost','Organik atık kontrollü çürütülerek toprağın yapısını iyileştiren humusa dönüşür.'],
 ['Sera','Sıcaklık, nem ve ışık kontrolü sezon dışı üretime imkân verir.'],
 ['Tohum Islahı','Seçilim ve melezleme ile verim, dayanıklılık ve kalite kuşaklar boyunca artırılır.'],
 ['Hasat Zamanı','Erken hasat olgunlaşmayı, geç hasat kaybı artırır; zamanlama kaliteyi belirler.'],
],
orman: [
 ['Ekosistem Servisleri','Orman su düzenler, toprağı tutar, karbon depolar ve iklimi yumuşatır.'],
 ['Karbon Yutağı','Ağaçlar büyürken karbon depolar; yaşlı ormanlar büyük bir stok tutar.'],
 ['Süksesyon','Bozulan alan otlarla başlar ve kademeli olarak olgun ormana ilerler.'],
 ['Tür Çeşitliliği','Karışık ormanlar, tek türlü plantasyonlardan hastalıklara çok daha dayanıklıdır.'],
 ['Yangın Ekolojisi','Bazı türlerin kozalağı ancak yangın sıcağıyla açılır; ateş doğal bir süreçtir.'],
 ['Yangın Önleme','Ölü örtünün azaltılması ve yangın şeritleri, yayılmayı yavaşlatan temel önlemlerdir.'],
 ['Toprak Erozyonu','Ağaç örtüsü kalkınca yağmur toprağı doğrudan döver ve üst verimli katman yıkanır.'],
 ['Sürdürülebilir Kesim','Yıllık artımdan fazlası kesilmezse orman varlığı azalmaz.'],
 ['Ağaçlandırma','Yanlış türle yapılan ağaçlandırma su rejimini bozabilir; tür yerel koşula göre seçilir.'],
 ['Yaban Hayat Koridoru','Parçalanmış habitatları bağlayan şeritler genetik alışverişi sürdürür.'],
 ['Odun Dışı Ürünler','Mantar, reçine ve bal gibi ürünler ormanı kesmeden gelir sağlar.'],
 ['Envanter','Ağaç çapı ve boyu örnek alanlarda ölçülerek tüm ormanın serveti tahmin edilir.'],
],
arkeoloji: [
 ['Stratigrafi','Katmanlar üst üste birikir; alttaki katman kural olarak daha eskidir.'],
 ['Karbon 14','Organik kalıntılardaki radyoaktif karbon azalışına bakarak yaklaşık yaş bulunur.'],
 ['Bağlam','Buluntunun nerede ve neyle birlikte bulunduğu, nesnenin kendisinden daha değerlidir.'],
 ['Kazı Karesi','Alan ızgaraya bölünür; her buluntunun konumu üç boyutlu olarak kaydedilir.'],
 ['Höyük','Aynı yerde üst üste kurulan yerleşimlerin oluşturduğu yapay tepedir.'],
 ['Seramik Tipolojisi','Çanak biçimleri dönemlere göre değişir; kırık bir parça bile tarihleme sağlar.'],
 ['Litik Buluntu','Taş alet üretim artıkları, teknolojinin ve günlük yaşamın izini taşır.'],
 ['Arkeobotanik','Kömürleşmiş tohumlar, geçmiş tarım ve beslenme düzenini ortaya çıkarır.'],
 ['Zooarkeoloji','Hayvan kemikleri avcılık, evcilleştirme ve et tüketimi hakkında bilgi verir.'],
 ['Koruma','Topraktan çıkan nesne aniden ortam değiştirir; ilk saatlerde bozulma en hızlıdır.'],
 ['Jeofizik Tarama','Kazı yapmadan yer radarı ile toprak altındaki yapılar haritalanabilir.'],
 ['Yayın','Kazılmış ama yayımlanmamış alan, bilim için kaybolmuş sayılır.'],
],
madencilik: [
 ['Cevher','İçindeki metalin çıkarılması ekonomik olan kayaca cevher denir.'],
 ['Tenör','Cevherdeki değerli metal oranıdır; düşük tenör daha çok kaya işlemek demektir.'],
 ['Açık Ocak','Yüzeye yakın yataklarda basamaklar hâlinde kazılır; maliyeti düşük, alan etkisi büyüktür.'],
 ['Yeraltı Madenciliği','Derin yataklarda galeriler açılır; havalandırma ve tahkimat hayati önemdedir.'],
 ['Tahkimat','Galeri tavanı ve yanları desteklenerek göçük riski kontrol altına alınır.'],
 ['Havalandırma','Temiz hava sürekli sirküle edilerek metan ve toz birikimi engellenir.'],
 ['Grizu','Kömür damarlarından çıkan metan, belirli oranda hava ile patlayıcı karışım oluşturur.'],
 ['Flotasyon','Öğütülen cevherde değerli mineraller köpük yüzeyine bağlanarak ayrılır.'],
 ['Atık Barajı','İşlem artıkları depolanır; barajın yıkılması en ağır çevre kazalarından biridir.'],
 ['Sondaj','Karot örnekleri alınarak yatağın büyüklüğü ve kalitesi kazı öncesi belirlenir.'],
 ['Rehabilitasyon','Ocak kapandıktan sonra arazi yeniden şekillendirilip bitkilendirilir.'],
 ['İş Güvenliği','Toz, gürültü ve titreşim uzun vadeli meslek hastalıklarının başlıca nedenleridir.'],
],
cografya: [
 ['Enlem ve Boylam','Enlem kuzey-güney, boylam doğu-batı konumu verir; ikisi birlikte tek bir noktayı tanımlar.'],
 ['Ölçek','Haritadaki uzunluğun gerçekteki karşılığıdır; büyük ölçek daha ayrıntı gösterir.'],
 ['Projeksiyon','Küre düzleme aktarılırken mutlaka bozulma olur; hangi özelliğin korunacağı seçilir.'],
 ['İzohips','Eş yükselti eğrileridir; sık çizgi dik yamaç, seyrek çizgi düz araziyi gösterir.'],
 ['İklim Kuşakları','Enlem, yükselti, denize uzaklık ve akıntılar iklimi birlikte belirler.'],
 ['Nüfus Yoğunluğu','Birim alana düşen kişi sayısıdır; ortalama, dağılımdaki uçları gizler.'],
 ['Göç','İtici ve çekici etkenler birlikte çalışır; ekonomik nedenler çoğu göçte başrolü oynar.'],
 ['Kentleşme','Kentler dünya yüzeyinin küçük bir kısmını kaplar ama nüfusun yarısından fazlasını barındırır.'],
 ['Akarsu Havzası','Yağışın toplanıp aynı akarsuya aktığı alandır; su yönetimi havza ölçeğinde yapılır.'],
 ['Doğal Afet Riski','Risk, tehlike ile kırılganlığın çarpımıdır; aynı deprem farklı yerlerde farklı sonuç doğurur.'],
 ['CBS','Coğrafi bilgi sistemleri, katmanlı veriyi harita üzerinde birlikte analiz eder.'],
 ['Saat Dilimleri','Dünya 24 dilime ayrılmıştır; her 15 boylam derecesi bir saatlik farka karşılık gelir.'],
],
});

Object.assign(KONULAR, {
hukuk: [
 ['Hukuk Devleti','Devletin kendisi de koyduğu kurallarla bağlıdır; keyfî yönetimin karşıtıdır.'],
 ['Masumiyet Karinesi','Kesin hüküm verilene kadar herkes suçsuz sayılır; ispat yükü iddia edende olur.'],
 ['Kanunilik İlkesi','Kanunda açıkça suç sayılmayan bir eylem cezalandırılamaz.'],
 ['Geriye Yürümezlik','Kural olarak yeni kanun geçmişteki olaylara uygulanmaz; lehe hükümler istisnadır.'],
 ['Sözleşme Serbestisi','Taraflar içeriği belirlemekte serbesttir ama emredici kurallara aykırı olamaz.'],
 ['İyi Niyet','Hakların kullanımı dürüstlük kuralına bağlıdır; kötüye kullanım korunmaz.'],
 ['Kusur','Sorumluluk çoğu zaman kast ya da ihmalin varlığına bağlanır.'],
 ['Zamanaşımı','Hak, belirli süre kullanılmazsa dava yoluyla istenemez hâle gelebilir.'],
 ['İspat','Hukukta gerçeğin kendisi değil, usulüne uygun ispatlanabilen kısmı hüküm doğurur.'],
 ['Delil','Hukuka aykırı yolla elde edilen delil, kural olarak hükme esas alınamaz.'],
 ['Temyiz','Karar üst mahkemede esas değil, hukuka uygunluk yönünden denetlenir.'],
 ['Hakkaniyet','Katı kural uygulaması aşırı sonuç doğurduğunda hâkim dengeyi gözetir.'],
],
ekonomi: [
 ['Arz ve Talep','Fiyat, alıcı ile satıcının isteklerinin kesiştiği noktada oluşur.'],
 ['Fırsat Maliyeti','Bir seçimin gerçek bedeli, vazgeçilen en iyi alternatiftir.'],
 ['Enflasyon','Genel fiyat düzeyinin sürekli artmasıdır; paranın satın alma gücünü düşürür.'],
 ['Faiz','Paranın zaman değeridir; bugünkü tüketimden vazgeçmenin karşılığıdır.'],
 ['GSYH','Bir ülkede belirli dönemde üretilen nihai mal ve hizmetlerin toplam değeridir.'],
 ['Arz Şoku','Üretim maliyetini artıran ani olaylar hem enflasyonu hem işsizliği birlikte yükseltebilir.'],
 ['Karşılaştırmalı Üstünlük','Ülkeler her şeyi değil, göreli olarak daha ucuz ürettiklerini üretip ticaret yapar.'],
 ['Para Politikası','Merkez bankası faiz ve likidite ile talebi ve fiyat istikrarını yönlendirir.'],
 ['Maliye Politikası','Vergi ve kamu harcaması ekonomideki toplam talebi doğrudan etkiler.'],
 ['Bileşik Getiri','Kazancın da kazanmaya başlaması, uzun sürede etkiyi katlar.'],
 ['Çeşitlendirme','Riski dağıtmak, tek bir varlıktaki dalgalanmanın etkisini azaltır.'],
 ['Piyasa Başarısızlığı','Dışsallık ve bilgi eşitsizliği olduğunda piyasa tek başına verimli sonuç üretmez.'],
],
isletme: [
 ['Değer Önerisi','Müşterinin hangi sorununu, rakiplerden farklı olarak nasıl çözdüğünün net cevabıdır.'],
 ['Hedef Kitle','Herkese satmaya çalışmak, kimseye satamamanın en yaygın yoludur.'],
 ['Birim Ekonomisi','Tek bir satıştan kalan kâr negatifse, ölçek büyütmek zararı büyütür.'],
 ['Nakit Akışı','Kârlı görünen şirketler çoğu zaman nakit yetersizliğinden batar.'],
 ['Sabit ve Değişken Maliyet','Sabit maliyet üretimden bağımsızdır; başabaş noktası bu ayrımla hesaplanır.'],
 ['Başabaş Noktası','Toplam gelirin toplam maliyeti karşıladığı satış düzeyidir.'],
 ['MVP','En küçük çalışan ürünle varsayımı erken test etmek, uzun geliştirmeden ucuzdur.'],
 ['Müşteri Edinme Maliyeti','Bir müşteriyi kazanmanın bedeli, o müşterinin yaşam boyu değerinden düşük olmalıdır.'],
 ['Elde Tutma','Mevcut müşteriyi tutmak, yeni müşteri kazanmaktan genellikle çok daha ucuzdur.'],
 ['Rekabet Avantajı','Kolay taklit edilen üstünlük avantaj değildir; kalıcılık kaynağı önemlidir.'],
 ['Delegasyon','Kurucu her işi kendi yaparsa şirket kurucunun kapasitesinde sıkışır.'],
 ['Kilit Gösterge','Ölçülen şey yönetilir; ama yanlış gösterge yanlış davranışı ödüllendirir.'],
],
egitim: [
 ['Öğrenme Hedefi','İyi hedef, öğrencinin ders sonunda ne yapabileceğini gözlenebilir biçimde tanımlar.'],
 ['Ön Bilgi','Yeni bilgi mevcut bilginin üzerine oturur; eksik temel her şeyi yavaşlatır.'],
 ['Bilişsel Yük','Aynı anda çok bilgi sunmak öğrenmeyi engeller; parçalara bölmek gerekir.'],
 ['Aralıklı Tekrar','Konular zamana yayılarak tekrar edildiğinde kalıcılık belirgin artar.'],
 ['Biçimlendirici Değerlendirme','Not vermek için değil, öğretimi yönlendirmek için yapılan ölçmedir.'],
 ['Geri Bildirim','Etkili geri bildirim doğru-yanlış demez; nasıl ilerleneceğini gösterir.'],
 ['Yapılandırmacılık','Öğrenci bilgiyi almaz, kendi zihninde yeniden kurar.'],
 ['Farklılaştırma','Aynı sınıfta farklı hazır bulunuşluk vardır; tek hız herkese uymaz.'],
 ['Sınıf Yönetimi','Açık rutinler ve beklentiler, disiplin sorunlarının çoğunu baştan önler.'],
 ['Gelişim Zihniyeti','Yeteneğin çabayla gelişebileceğine inanan öğrenciler zorlukta daha dirençlidir.'],
 ['Akran Öğretimi','Anlatan öğrenir; öğrenciye öğretme rolü vermek kavramayı derinleştirir.'],
 ['Ölçme Geçerliği','Bir sınav, ölçmek istediği şeyi gerçekten ölçüyorsa geçerlidir.'],
],
medya: [
 ['Haber Değeri','Güncellik, yakınlık, etki ve sıra dışılık bir olayı haber yapan temel ölçütlerdir.'],
 ['Beş N Bir K','Ne, nerede, ne zaman, neden, nasıl ve kim sorularının cevabı haberin iskeletidir.'],
 ['Ters Piramit','En önemli bilgi başa yazılır; okuyucu her an bıraksa bile özü almış olur.'],
 ['Kaynak Doğrulama','Tek kaynak yeterli değildir; bağımsız ikinci doğrulama temel kuraldır.'],
 ['Tarafsızlık','Her görüşe eşit yer vermek, kanıt eşit değilse yanlış denge yaratır.'],
 ['Çerçeveleme','Aynı olay farklı çerçevelenince okuyucuda bambaşka bir algı oluşur.'],
 ['Manşet Etiği','Metinle uyumsuz manşet, yanlış bilginin en hızlı yayılan biçimidir.'],
 ['Kaynak Gizliliği','Muhabir kaynağını korur; bu güven olmadan kamu yararına haber üretilemez.'],
 ['Dezenformasyon','Kasıtlı yanlış bilgi, doğru bilgiden daha hızlı yayılma eğilimindedir.'],
 ['Görsel Doğrulama','Fotoğrafın tarihi ve yeri, ters görsel arama ve meta veriyle sınanır.'],
 ['Veri Gazeteciliği','Sayılar bağlamı olmadan yanıltır; oran, dönem ve karşılaştırma verilmelidir.'],
 ['Düzeltme','Hata yapıldığında görünür biçimde düzeltmek, güveni azaltmaz aksine artırır.'],
],
tarih: [
 ['Kaynak Eleştirisi','Birincil kaynak olaya tanık olandır; ikincil kaynak onu yorumlar.'],
 ['Kronoloji','Olayların sırası, neden-sonuç ilişkisini kurmanın ilk şartıdır.'],
 ['Neolitik Devrim','Yaklaşık 12 bin yıl önce tarıma geçiş, yerleşik yaşamı ve şehirleri doğurdu.'],
 ['Yazının İcadı','Sümer’de yaklaşık M.Ö. 3200’de ortaya çıktı; tarih öncesi ile tarihi ayıran çizgidir.'],
 ['İmparatorluk','Geniş toprakları yöneten devletler yol, ortak para ve idare ile bütünlük kurar.'],
 ['Matbaa','15. yüzyılda hareketli harflerle baskı, bilginin yayılma hızını kökten değiştirdi.'],
 ['Coğrafi Keşifler','Yeni deniz yolları ticareti, bitkileri ve hastalıkları kıtalar arasında taşıdı.'],
 ['Sanayi Devrimi','Buhar gücü üretimi fabrikaya taşıdı ve toplumsal yapıyı yeniden kurdu.'],
 ['Fransız Devrimi','Egemenliğin kaynağını hükümdardan halka taşıyan modern siyasetin dönüm noktasıdır.'],
 ['Dünya Savaşları','20. yüzyılın iki büyük savaşı sınırları, teknolojiyi ve uluslararası düzeni değiştirdi.'],
 ['Sözlü Tarih','Tanıkların anlatısı, belgelerde görünmeyen gündelik yaşamı kayda geçirir.'],
 ['Anakronizm','Geçmişi bugünün değerleriyle yargılamak, tarihsel anlamayı bozar.'],
],
dilbilim: [
 ['Fonem','Anlam ayırt eden en küçük ses birimidir; dilden dile sayısı değişir.'],
 ['Morfem','Anlam taşıyan en küçük yapı birimidir; kökler ve ekler morfemdir.'],
 ['Sözdizimi','Kelimelerin cümlede dizilme kurallarıdır; anlam çoğu zaman sıradan doğar.'],
 ['Anlambilim','Kelime ve cümlenin düz anlamını inceler; bağlamdan bağımsız katmandır.'],
 ['Edimbilim','Aynı cümle bağlama göre farklı iş görür; rica, emir ya da şaka olabilir.'],
 ['Dil Ailesi','Ortak atadan gelen diller aile oluşturur; Türkçe ve Fince farklı ailelerdendir.'],
 ['Ses Değişimi','Diller zaman içinde düzenli ses değişimlerine uğrar; bu kurallar akrabalığı gösterir.'],
 ['Ödünçleme','Diller birbirinden kelime alır; alınan kelime çoğu zaman ses yapısına uydurulur.'],
 ['Ana Dil Edinimi','Çocuk kuralları ezberleyerek değil, veriden çıkararak öğrenir.'],
 ['İki Dillilik','İki dil kullanmak dikkat ve geçiş becerilerini destekleyen bir zihinsel egzersizdir.'],
 ['Çeviri Eşdeğerliği','Kelime kelime çeviri anlamı taşımaz; hedef dilde aynı etkiyi yaratmak esastır.'],
 ['Deyim','Deyimler parçalarının toplamından farklı anlam taşır; birebir çevrilemez.'],
],
muzik: [
 ['Nota Süresi','Birlik, ikilik ve dörtlük notalar süreyi ikişer kat bölerek ritmi kurar.'],
 ['Ölçü','Müzik eşit zaman kutularına bölünür; 4/4 en yaygın ölçüdür.'],
 ['Tempo','Dakikadaki vuruş sayısıdır; aynı eser tempoyla bambaşka karakter kazanır.'],
 ['Aralık','İki ses arasındaki mesafedir; oktav aynı sesin iki katı frekansıdır.'],
 ['Akor','Üç ya da daha çok sesin birlikte tınlamasıdır; majör aydınlık, minör hüzünlü duyulur.'],
 ['Tonalite','Bir eser merkezî bir sese yerleşir; kulak o sese dönmeyi bekler.'],
 ['Armoni','Akorların birbirini izleme mantığıdır; gerilim ve çözülme bu sırayla kurulur.'],
 ['Melodi','Yatay çizgidir; iyi melodi hem tekrar hem sürpriz içerir.'],
 ['Dinamik','Ses şiddetinin değişimi, ifadenin en güçlü aracıdır.'],
 ['Timbre','Aynı notayı çalan iki enstrümanı ayıran renk farkıdır; üst harmoniklerden doğar.'],
 ['Senkop','Vurgu beklenmedik zamana kayınca ritim canlanır.'],
 ['Deşifre','Notayı ilk görüşte çalabilmek, kalıpları tanımakla gelişen bir beceridir.'],
],
sanat: [
 ['Kompozisyon','Elemanların yüzeye yerleşimi, konudan çok daha fazla etki belirler.'],
 ['Üçte Bir Kuralı','Yüzey üçe bölünür; ilgi noktaları kesişimlere yerleştirilince denge doğar.'],
 ['Değer','Açık-koyu farkı, biçimi renkten çok daha güçlü kurar.'],
 ['Perspektif','Uzaktaki nesneler küçülür ve kaçış noktasında birleşir; derinlik böyle yaratılır.'],
 ['Renk Çemberi','Karşıt renkler yan yana geldiğinde birbirini güçlendirir.'],
 ['Sıcak-Soğuk','Sıcak renkler öne çıkar, soğuk renkler geri çekilir; derinlik renkle de kurulur.'],
 ['Negatif Alan','Nesnenin çevresindeki boşluğu çizmek, biçimi görmenin en hızlı yoludur.'],
 ['Kontur','Kaleme bakmadan konturu izlemek, el ile gözü senkronlar.'],
 ['Oran','Yüz ve figür çiziminde ölçüler birbiriyle karşılaştırılarak bulunur.'],
 ['Işık ve Gölge','Ana ışık, yarı ton, gölge ve yansıyan ışık hacim yanılsamasını oluşturur.'],
 ['Doku','Yüzeyin hissi, fırça izi ve malzeme seçimiyle aktarılır.'],
 ['Eskiz','Hızlı ve çok sayıda eskiz, tek bir mükemmel denemeden daha çok öğretir.'],
],
ascilik: [
 ['Maillard Tepkimesi','Yüksek ısıda protein ve şeker tepkimeye girer; kızarma lezzetinin kaynağıdır.'],
 ['Karamelizasyon','Şeker ısıyla parçalanıp yüzlerce yeni aroma bileşiği üretir.'],
 ['Tuz','Tuz yalnızca tuzluluk vermez, diğer tatları da belirginleştirir.'],
 ['Asit Dengesi','Bir tabak ağır geliyorsa çoğu zaman eksik olan asittir; limon dengeyi kurar.'],
 ['Emülsiyon','Yağ ve su bir bağlayıcı ile karışır; mayonez ve sos bu ilkeye dayanır.'],
 ['Dinlendirme','Pişen et dinlenince su liflere geri dağılır ve kesim daha sulu olur.'],
 ['Mise en Place','Her malzeme önceden hazırlanır; pişirme sırasında hız ve kontrol bundan doğar.'],
 ['Bıçak Tekniği','Düzgün doğranan malzeme eşit pişer; teknik hız değil eşitlik meselesidir.'],
 ['Isı Aktarımı','İletim, taşınım ve ışıma farklı pişirme yöntemlerinin temelini oluşturur.'],
 ['Fermantasyon','Mikroorganizmalar şekeri dönüştürerek hem koruma hem derin aroma sağlar.'],
 ['Umami','Beşinci temel tattır; mantar, domates ve peynirde belirgin biçimde bulunur.'],
 ['Tabak Sunumu','Yükseklik, boşluk ve renk kontrastı, lezzet algısını gerçekten değiştirir.'],
],
});
