/* ===== SPOR & EGZERSİZ ALANLARI — 10 alan x 10 konu ===== */
const SPOR_ALANLAR = [
  {id:'sinav',   n:'Şınav & İtiş',        e:'💪', g:'spor', skin:'push',  a:'#ff9d7a', b:'#c2410c', grp:'Spor'},
  {id:'kardiyo2',n:'Kardiyo & Dayanıklılık',e:'🏃',g:'spor', skin:'run',   a:'#7dd3fc', b:'#0369a1', grp:'Spor'},
  {id:'kuvvet',  n:'Kuvvet Antrenmanı',   e:'🏋️', g:'spor', skin:'lift',  a:'#fbbf24', b:'#a16207', grp:'Spor'},
  {id:'core',    n:'Core & Karın',        e:'🤸', g:'spor', skin:'core',  a:'#a3e635', b:'#4d7c0f', grp:'Spor'},
  {id:'esneklik',n:'Esneklik & Mobilite', e:'🧘', g:'spor', skin:'flex',  a:'#c4b5fd', b:'#6d28d9', grp:'Spor'},
  {id:'hiit',    n:'HIIT & İnterval',     e:'⏱️', g:'spor', skin:'hiit',  a:'#fb7185', b:'#9f1239', grp:'Spor'},
  {id:'yuzme',   n:'Yüzme',               e:'🏊', g:'spor', skin:'swim',  a:'#67e8f9', b:'#0e7490', grp:'Spor'},
  {id:'bisiklet',n:'Bisiklet',            e:'🚴', g:'spor', skin:'bike',  a:'#86efac', b:'#15803d', grp:'Spor'},
  {id:'kalisten',n:'Barfiks & Kalistenik',e:'🧗', g:'spor', skin:'bar',   a:'#f0abfc', b:'#86198f', grp:'Spor'},
  {id:'toparlan',n:'Toparlanma & Sakatlık',e:'🧊',g:'spor', skin:'rec',   a:'#93c5fd', b:'#1d4ed8', grp:'Spor'},
];

const SPOR_KONULAR = {
sinav: [
 ['Doğru Şınav Formu','Eller omuz hizasından biraz geniş, gövde baştan topuğa tek bir düz çizgi hâlinde kalmalıdır.'],
 ['Dirsek Açısı','Dirsekler gövdeye 45 derece açıyla açılır; tam yana açmak omuz eklemini zorlar.'],
 ['Diz Üstü Şınav','Tam şınav gelmiyorsa dizden yapılan versiyon aynı kasları daha az yükle çalıştırır.'],
 ['Duvar Şınavı','Başlangıç seviyesi için duvara karşı yapılan itiş, hareket kalıbını güvenle öğretir.'],
 ['Eğimli ve Ters Eğimli','Elleri yükseltmek hareketi kolaylaştırır, ayakları yükseltmek üst göğsü ve omzu zorlar.'],
 ['Elmas Şınav','Eller birleşik yapılan varyasyon yükü belirgin biçimde triceps kasına kaydırır.'],
 ['Tempo','İnişi üç saniyede yapmak, hızlı tekrardan çok daha fazla kas gerilimi üretir.'],
 ['Solunum','İnerken nefes alınır, iterken verilir; nefes tutmak kan basıncını gereksiz yükseltir.'],
 ['Kademeli Artış','Haftada tekrar sayısını yaklaşık yüzde on artırmak, omuz ve bilek yüklenmesini güvenli tutar.'],
 ['Bilek Ağrısı','Bilek acıyorsa yumruk üstünde ya da tutamak üzerinde çalışmak eklemi nötr konumda tutar.'],
],
kardiyo2: [
 ['Aerobik ve Anaerobik','Düşük şiddette enerji oksijenle üretilir; şiddet artınca vücut oksijensiz yola geçer.'],
 ['Maksimum Nabız','Kaba tahmin 220’den yaş çıkarılarak yapılır; kişisel ölçüm her zaman daha doğrudur.'],
 ['Nabız Bölgeleri','Düşük bölge yağ oksidasyonunu, yüksek bölge kalp kapasitesini geliştirir.'],
 ['Konuşma Testi','Konuşabiliyor ama şarkı söyleyemiyorsan orta şiddettesin demektir.'],
 ['VO2 Maks','Vücudun dakikada kullanabildiği en yüksek oksijen miktarıdır ve dayanıklılığın en iyi göstergesidir.'],
 ['Kolay Koşu','Antrenmanın büyük kısmı rahat tempoda yapılmalıdır; her gün zorlamak gelişimi durdurur.'],
 ['Adım Frekansı','Dakikada yaklaşık 170-180 adım, aşırı uzun adımın yarattığı fren etkisini azaltır.'],
 ['Isınma','Beş on dakikalık kademeli ısınma, kalp atışını ve kas sıcaklığını güvenli biçimde yükseltir.'],
 ['Soğuma','Aniden durmak yerine tempoyu düşürerek bitirmek, kan birikimini ve baş dönmesini önler.'],
 ['Hacim Artışı','Haftalık toplam mesafeyi yüzde on kuralının üzerinde artırmak sakatlık riskini yükseltir.'],
],
kuvvet: [
 ['Aşırı Yükleme','Kas ancak alıştığından biraz fazlasıyla karşılaşınca gelişir.'],
 ['Progresif Yükleme','Ağırlık, tekrar ya da set kademeli artırılmadığında ilerleme durur.'],
 ['Tekrar Aralığı','Düşük tekrar ağır yükle kuvveti, orta tekrar kas hacmini öne çıkarır.'],
 ['Set Arası Dinlenme','Ağır setlerde iki üç dakika beklemek, sonraki setin kalitesini korur.'],
 ['Bileşik Hareket','Squat, deadlift ve bench birçok kası aynı anda çalıştırır; verim en yüksektir.'],
 ['İzolasyon Hareketi','Tek eklemi çalıştırır; zayıf kalan bölgeyi hedeflemek için kullanılır.'],
 ['Form Önceliği','Bozuk formla kaldırılan ağırlık kazanç değil, sakatlık riskidir.'],
 ['Toparlanma','Kas antrenmanda değil dinlenirken büyür; aynı bölge genelde 48 saat beklemelidir.'],
 ['Süperkompanzasyon','Yorgunluk geçtikten sonra vücut eski seviyenin biraz üstüne çıkar; asıl kazanç budur.'],
 ['Deload Haftası','Her birkaç haftada yükü azaltmak, birikmiş yorgunluğu temizler ve ilerlemeyi sürdürür.'],
],
core: [
 ['Core Nedir','Karın, sırt, kalça ve pelvis tabanı kaslarının oluşturduğu merkezi destek sistemidir.'],
 ['Stabilite','Core’un asıl işi hareket üretmek değil, omurgayı istenmeyen harekete karşı sabitlemektir.'],
 ['Plank','Kalça ne yukarı kalkmalı ne çökmelidir; süre değil hizalanma önceliklidir.'],
 ['Nötr Omurga','Bel ne aşırı çukur ne aşırı düz; doğal eğri korunarak çalışılır.'],
 ['Karın İçi Basınç','Doğru nefes ve kasılma omurgaya içeriden destek verir; ağır kaldırışta kritiktir.'],
 ['Ölü Böcek','Zıt kol ve bacak uzatılırken bel yerden kalkmıyorsa hareket doğru yapılıyordur.'],
 ['Yan Plank','Gövdenin yan zincirini çalıştırır; kalça düşmeden tutulması esastır.'],
 ['Kalça Köprüsü','Kalça kaslarını çalıştırırken bel yerine kalçayı çalıştırmayı öğretir.'],
 ['Mekik Sınırı','Çok sayıda klasik mekik bel disklerini tekrarlayan bükülmeye maruz bırakır.'],
 ['Nefes ve Core','Nefesi tutmak yerine kontrollü vermek, kasılmayı bozmadan basıncı yönetir.'],
],
esneklik: [
 ['Statik Germe','Pozisyonda 20-30 saniye kalmak esneklik için etkilidir; antrenman sonrasına uygundur.'],
 ['Dinamik Isınma','Antrenman öncesi kontrollü salınım hareketleri kası performansa hazırlar.'],
 ['Mobilite ve Esneklik','Esneklik pasif uzayabilmek, mobilite ise o aralıkta kontrollü hareket edebilmektir.'],
 ['Kalça Fleksörü','Uzun süre oturmak bu kası kısaltır ve bel ağrısının sık görülen sebebidir.'],
 ['Hamstring','Arka bacak kısalığı öne eğilmede beli aşırı yükler.'],
 ['Torasik Rotasyon','Sırt üst bölgesinin dönmesi azalınca omuz ve bel telafi etmeye çalışır.'],
 ['Ayak Bileği Mobilitesi','Kısıtlı ayak bileği, squat derinliğini ve diz sağlığını doğrudan etkiler.'],
 ['Sinir Gerilimi','Karıncalanma varsa germe değil sinir gerilimi olabilir; zorlanmamalıdır.'],
 ['Foam Roller','Yumuşak doku üzerinde yavaş yuvarlanmak dolaşımı artırır ve hareket açıklığını geçici genişletir.'],
 ['Düzenlilik','Esneklik uzun süreli ve sık tekrar ister; haftada bir uzun seans yeterli değildir.'],
],
hiit: [
 ['İnterval Mantığı','Yüksek şiddetli kısa çalışmalar ve toparlanma dönemleri dönüşümlü uygulanır.'],
 ['İş-Dinlenme Oranı','Başlangıçta bire iki, ileri seviyede bire bir oran yaygın olarak kullanılır.'],
 ['Tabata','Yirmi saniye maksimum çalışma ve on saniye dinlenme sekiz tur boyunca tekrarlanır.'],
 ['EPOC','Yoğun çalışma sonrası vücut saatlerce yükselmiş metabolizmayla toparlanmaya devam eder.'],
 ['Şiddet Kontrolü','HIIT gerçekten yüksek şiddet gerektirir; orta tempoda yapılırsa interval olmaktan çıkar.'],
 ['Sıklık Sınırı','Haftada iki üç seanstan fazlası toparlanmayı bozar ve performansı düşürür.'],
 ['Hareket Seçimi','Karmaşık teknik gerektiren hareketler yorgunlukta bozulur; basit kalıplar daha güvenlidir.'],
 ['Isınma Zorunluluğu','Soğuk kasla ani yüksek şiddet, sakatlanmanın en yaygın nedenidir.'],
 ['Başlangıç Uyarlaması','Yeni başlayanlar için yürüyüş-koşu dönüşümü, güvenli bir interval biçimidir.'],
 ['Bitiş Sinyali','Form bozulmaya başladığında seans biter; sayı tamamlamak amaç değildir.'],
],
yuzme: [
 ['Su Direnci','Direnç hızın karesiyle artar; teknik iyileştirmesi güçten daha çok kazandırır.'],
 ['Vücut Pozisyonu','Kalça yüzeye yakın ve yatay tutulduğunda sürüklenme belirgin azalır.'],
 ['Nefes Ritmi','Nefes suyun içinde verilir; yalnızca alma anı yüzeyde gerçekleşir.'],
 ['Serbest Stil','En hızlı stildir; gövde dönüşü kolun su tutma mesafesini uzatır.'],
 ['Kurbağalama','Kol ve bacak zamanlaması kritik olduğu için en teknik stillerden biridir.'],
 ['Su Tutma','Avuç suyu itmek yerine sabit tutup vücudu ileri çekmek olarak düşünülür.'],
 ['Ayak Vuruşu','Vuruş dizden değil kalçadan başlar; ayak bileği gevşek kalmalıdır.'],
 ['Dönüş','Duvar dönüşü, mesafenin önemli bir bölümünde hız kazanma fırsatıdır.'],
 ['Omuz Sağlığı','Yüksek hacimli yüzmede omuz sıkışması sıktır; sırt kasları dengeleyici çalıştırılır.'],
 ['Güvenlik','Tek başına ve gözetimsiz yüzülmez; yorgunluk suda çok hızlı gelişir.'],
],
bisiklet: [
 ['Sele Yüksekliği','Pedal en alttayken diz hafif bükülü kalmalıdır; yanlış yükseklik diz ağrısı yapar.'],
 ['Kadans','Dakikada 80-100 devir, kasları daha az yorarak dolaşım sistemine yük aktarır.'],
 ['Vites Mantığı','Yokuşta hafif vitesle yüksek kadans, ağır vitesle zorlamaktan daha verimlidir.'],
 ['Aerodinamik','Yüksek hızda direncin büyük kısmı vücut duruşundan kaynaklanır.'],
 ['Yuvarlak Pedal','Sadece basmak değil, çekiş ve geçiş fazlarını da kullanmak verimi artırır.'],
 ['Fren Dengesi','Ön fren gücün çoğunu verir ama ani kullanımı savrulmaya yol açar.'],
 ['Lastik Basıncı','Düşük basınç direnci artırır, aşırı basınç yol tutuşunu ve konforu düşürür.'],
 ['Uzun Sürüş Beslenmesi','Bir saatin üzerindeki sürüşlerde düzenli karbonhidrat ve sıvı alımı gerekir.'],
 ['Görünürlük','Işık ve reflektör, gündüz bile görünürlüğü ve güvenliği belirgin artırır.'],
 ['Bakım','Zincir yağı, fren balatası ve lastik kontrolü her sürüş öncesi hızlıca gözden geçirilir.'],
],
kalisten: [
 ['Kendi Ağırlığı','Ekipman olmadan vücut ağırlığıyla ilerleyici yükleme kurulabilir.'],
 ['Negatif Tekrar','Barfikste yalnız iniş fazını yavaş yapmak, ilk tekrara giden en etkili yoldur.'],
 ['Skapula Kontrolü','Barfikse omuz kürekleri aşağı ve geriye çekilerek başlanır; omuz böyle korunur.'],
 ['Pull-up ve Chin-up','Avuç dışa bakınca sırt, içe bakınca biceps daha çok devreye girer.'],
 ['Dips','Gövde dik tutulunca triceps, öne eğilince göğüs ağırlık alır.'],
 ['Lastik Desteği','Direnç lastiği yükün bir kısmını taşır ve tam tekrara geçişi kademelendirir.'],
 ['Kol Duruşu','Denge çalışmaları önce duvar desteğiyle, kontrollü ve kısa tutuşlarla öğrenilir.'],
 ['İskelet Yükü','Eklem ve tendon kastan daha yavaş uyum sağlar; ilerleme bu hıza göre ayarlanır.'],
 ['Hacim Yönetimi','Her gün maksimum tekrar yapmak yerine, günlere yayılmış setler daha çok ilerletir.'],
 ['El Bakımı','Bar üzerinde nasır çatlamasını önlemek için tutuş ve nem kontrolü gerekir.'],
],
toparlan: [
 ['Uyku','Kas onarımı ve hormon salınımının büyük kısmı derin uyku sırasında gerçekleşir.'],
 ['Aktif Toparlanma','Hafif tempoda hareket, tam dinlenmeye göre kan akışını artırıp ağrıyı azaltabilir.'],
 ['Gecikmiş Kas Ağrısı','Yeni bir yüklenmeden bir iki gün sonra ortaya çıkar ve normalde birkaç günde geçer.'],
 ['Aşırı Antrenman','Performans düşüşü, uyku bozukluğu ve isteksizlik birlikte görülüyorsa yük fazladır.'],
 ['Sıvı ve Elektrolit','Terle kaybedilen su ve tuz yerine konmazsa kramp ve performans kaybı görülür.'],
 ['Protein Zamanlaması','Günlük toplam protein en belirleyicidir; öğünlere yayılması toparlanmayı destekler.'],
 ['Buz ve Sıcak','Akut şişlikte soğuk, kronik sertlikte sıcak uygulama daha uygundur.'],
 ['Ağrı Sinyali','Keskin ve eklem içinde hissedilen ağrı, kas yorgunluğundan farklıdır ve durmayı gerektirir.'],
 ['Kademeli Dönüş','Sakatlık sonrası yük, ağrısız aralıkta kalarak adım adım artırılır.'],
 ['Isınma ve Soğuma','Kısa ısınma sakatlanma riskini düşürür; soğuma dolaşımı kademeli normale döndürür.'],
],
};
